src/objects/AccountHub__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountsHubs</relationshipLabel>
        <relationshipName>AccountsHubs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>AccountsHubs</relationshipLabel>
        <relationshipName>AccountsHubs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AccountHub</label>
    <nameField>
        <displayFormat>AH-{000000}</displayFormat>
        <label>AccountHub Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountsHubs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Building_Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Help Text Hub/Building Site</inlineHelpText>
        <label>Hub/Building Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Hub_Building_Site__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Building Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Site Location</value>
            </filterItems>
            <filterItems>
                <field>$Source.Hub_Building_Site__c</field>
                <operation>equals</operation>
                <valueField>Location__c.Hub_Building_Site__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bouwticket</label>
    <nameField>
        <displayFormat>BT-{00000}</displayFormat>
        <label>Naam van Building Ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bouwticket</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Hub_Building_Site__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Building Sites</relationshipLabel>
        <relationshipName>Hubs_Building_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Locatie</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locaties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projecten__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (klant)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Projectcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projecten</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/UserUtil.cls
public with sharing class UserUtil {
    public static void entry(TriggerParams triggerParams) {
        List<User> triggerNew = (List<User>)triggerParams.triggerNew;
        List<User> triggerOld = (List<User>)triggerParams.triggerOld;
        Map<Id, User> oldMap = (Map<Id, User>)triggerParams.oldMap;
        Map<Id, User> newMap = (Map<Id, User>)triggerParams.newMap;


        if (triggerParams.isAfter){
          if (triggerParams.isUpdate || triggerParams.isInsert) {
           Map <Id, Profile> profilesById = new Map <Id, Profile>([select Id from Profile 
                                                                    where Name = 'Bouwticket account' or Name = 'Bouwmanager']);
           System.debug('profilesById '+ profilesById);
           for(User user: triggerNew) {
                System.debug(user.ProfileId);
              System.debug(triggerParams.isUpdate && !profilesById.containsKey(oldMap.get(user.id).ProfileId ));
              System.debug(triggerParams.isUpdate && oldMap.get(user.Id).AccountId__c != newMap.get(user.Id).AccountId__c ) ;
                if ((triggerParams.isInsert 
                      || (triggerParams.isUpdate && !profilesById.containsKey(oldMap.get(user.id).ProfileId ) )
                      || (triggerParams.isUpdate && oldMap.get(user.Id).AccountId__c != newMap.get(user.Id).AccountId__c )
                      || (triggerParams.isUpdate && oldMap.get(user.Id).IsActive != newMap.get(user.Id).IsActive ))
                       && profilesById.containsKey(user.ProfileId) && newMap.get(user.Id).AccountId__c != null && newMap.get(user.Id).IsActive == true) {
                    System.debug(user.id);
                    System.debug(user.AccountId__c);
                            addNewSharing(user.id, newMap.get(user.Id).AccountId__c);
                            System.debug('*** SHARING WAS RUN ***');
                }
            }
          }
        }
    }
    @future
    public static void addNewSharing(Id userId, Id accId) {
      System.debug(userid);
        User user = [select Id, AccountId__c from User where id=: userId];
      user.AccountId__c = accId;
      System.debug(user);
        List <AccountShare> sharingAccount = [SELECT  AccountId, Id, UserOrGroupId 
                                                FROM AccountShare where UserOrGroupId =: user.id ];
        System.debug(sharingAccount.size() + ' ' + sharingAccount);
      try {
        delete sharingAccount;
      } catch(Exception e) {
          System.debug(e.getMessage());
      }

        AccountShare addShare = new AccountShare(UserOrGroupId = user.id, AccountId = user.AccountId__c, AccountAccessLevel = 'Edit',
                                                OpportunityAccessLevel = 'Edit', CaseAccessLevel = 'Edit', ContactAccessLevel = 'Edit');
        insert addShare;
        System.debug('toInsert ' +addShare);
        Map <Id, Building_Ticket__c> allowedBuildingTicketsById = new Map <Id, Building_Ticket__c>([select OwnerId, Id from Building_Ticket__c 
                                                                    where Hub_Building_Site__r.Project__r.Account__c =: user.AccountId__c]);
        List <Building_Ticket__Share> sharingTicket = [SELECT  ParentId, Id, UserOrGroupId , AccessLevel
                                                FROM Building_Ticket__Share where UserOrGroupId =: user.id and AccessLevel != 'All'];
        System.debug(sharingTicket.size() + ' ' + sharingTicket);

      try {
        Database.DeleteResult[] DR_Dels = Database.delete(sharingTicket);
        System.debug(DR_Dels);
        List <Building_Ticket__Share> sharingTicketOwner = [SELECT  Parent.OwnerId,  ParentId, Id, UserOrGroupId , AccessLevel
                          FROM Building_Ticket__Share where UserOrGroupId =: user.id and AccessLevel = 'All'];
        Set <Id> parentIds = new Set <Id>();
        for(Building_Ticket__Share sh: sharingTicketOwner) {
          parentIds.add(sh.ParentId);
        }
        Map <Id, Building_Ticket__c> ticketsById = new Map<Id, Building_Ticket__c>([select Id from Building_Ticket__c where id in:parentIds ]);
        User userAdmin = [select Id from User where (Profile.Name = 'System Administrator' or Profile.Name = 'Systeembeheerder') and isActive = true limit 1];
        List <Building_Ticket__c> toChangeOwner = new List <Building_Ticket__c>();
        for (Building_Ticket__Share sh: sharingTicketOwner) {
          Building_Ticket__c t = ticketsById.get(sh.ParentId);
          t.OwnerId = userAdmin.Id;
          toChangeOwner.add(t);
        }
        System.debug(toChangeOwner.size() + ' ' + toChangeOwner);

        update toChangeOwner;
      } catch(Exception e) {
          System.debug(e.getMessage());
      }
        
      
      List <Building_Ticket__Share> addTicketShare = new List <Building_Ticket__Share>();
      for (Building_Ticket__c t: allowedBuildingTicketsById.values()  ) {
        if (t.OwnerId != user.id) {
          Building_Ticket__Share sh = new Building_Ticket__Share(ParentId = t.id, UserOrGroupId = user.id,AccessLevel = 'Edit' );
          addTicketShare.add(sh);
        }
      }
      try {
        insert addTicketShare;
        System.debug('toInsert ' +addTicketShare);
      } catch(Exception e) {
        System.debug(e.getMessage());
      }
      
      Set <Id> hubIds = new Set <Id>();
      for (AccountHUB__c acHub: [select Id, Hub_Building_Site__c from AccountHUB__c  where Account__c =: user.AccountId__c]) {
          hubIDs.add(acHub.Hub_Building_Site__c );
      }
      System.debug('HUBIDS ' + hubIDs);
      Map <Id, Hub_Building_Site__c> hubs = new Map <Id, Hub_Building_Site__c>([select Id, Name from Hub_Building_Site__c 
                                                                              where Project__r.Account__c =: user.AccountId__c or Id in:hubIDs]);
      List<Hub_Building_Site__Share> hubShares = [select Id, ParentId from Hub_Building_Site__Share where UserOrGroupId =: user.id];
      
      try {
        delete hubShares;
      } catch(Exception e) {
          System.debug(e.getMessage());
      }
      
      List <Hub_Building_Site__Share> addHUbShare = new List <Hub_Building_Site__Share>();
      for (Hub_Building_Site__c t: hubs.values()  ) {
        Hub_Building_Site__Share sh = new Hub_Building_Site__Share(ParentId = t.id, UserOrGroupId = user.id,AccessLevel = 'Edit' );
          addHUbShare.add(sh);
      }
      insert addHUbShare;
      System.debug('toInsert addHUbShare' +addHUbShare); 

      Map <Id, Location__c> locations = new Map <Id, Location__c>([select Id, Name from Location__c 
                                                                              where Hub_Building_Site__r.Project__r.Account__c =: user.AccountId__c or Hub_Building_Site__c in: hubIDs]);
      List< Location__Share> locShares = [select Id, ParentId from Location__Share where UserOrGroupId =: user.id];
      try {
        delete locShares;
      } catch(Exception e) {
          System.debug(e.getMessage());
      }

      
      List <Location__Share> addLocShare = new List <Location__Share>();
      for (Location__c t: locations.values()  ) {
        Location__Share sh = new Location__Share(ParentId = t.id, UserOrGroupId = user.id,AccessLevel = 'Edit' );
        addLocShare.add(sh);
      }
      insert addLocShare;
      System.debug('toInsert addLocShare' +addLocShare);
      
      ////
      Map <Id, Projecten__c> projects = new Map <Id, Projecten__c>([select Id, Name from Projecten__c
                                                                              where Account__c =: user.AccountId__c ]);
      List< Projecten__Share> prShares = [select Id, ParentId from Projecten__Share where UserOrGroupId =: user.id];
      try {
        delete prShares ;
      } catch(Exception e) {
          System.debug(e.getMessage());
      }

      
      List <Projecten__Share> prShare = new List <Projecten__Share>();
      for (Projecten__c t: projects.values()  ) {
        Projecten__Share sh = new Projecten__Share(ParentId = t.id, UserOrGroupId = user.id,AccessLevel = 'Edit' );
        prShare.add(sh);
      }
      insert prShare;
      System.debug('toInsert addLocShare' +addLocShare);
    }
}