src/objects/AccountHub__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountsHubs</relationshipLabel>
        <relationshipName>AccountsHubs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>AccountsHubs</relationshipLabel>
        <relationshipName>AccountsHubs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AccountHub</label>
    <nameField>
        <displayFormat>AH-{000000}</displayFormat>
        <label>AccountHub Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountsHubs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Hub_Building_Site__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Building Sites</relationshipLabel>
        <relationshipName>Hubs_Building_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Available_amount__c</fullName>
        <label>Delivered to Project</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_amount__c</fullName>
        <label>Delivered to Hub</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Occupied__c</fullName>
        <formula>difference__c &gt; 0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>In gebruik</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sublocations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Locatie</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locaties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projecten__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (klant)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Projectcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projecten</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SublocationDetail__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>SublocationDetails</relationshipLabel>
        <relationshipName>SublocationDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_items__c</fullName>
        <formula>WWW_Detail__r.Number_Of_Items__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of  items</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WWW_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WWW-Detail</label>
        <referenceTo>WWW_Detail__c</referenceTo>
        <relationshipLabel>SublocationDetails</relationshipLabel>
        <relationshipName>SublocationDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SublocationDetail</label>
    <nameField>
        <displayFormat>SD-{0000}</displayFormat>
        <label>SublocationDetail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SublocationDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WWW_Detail__c.object
<CustomObject>
    <description>Who What Where
Wie Wat Waar</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Itemlocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_Of_Items__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Aantal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projectcode</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>WWW-Detail</relationshipLabel>
        <relationshipName>Itemlocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WWW-Detail</label>
    <nameField>
        <displayFormat>WWW-D-{0}</displayFormat>
        <label>WWW Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WWW-Detail</pluralLabel>
    <recordTypes>
        <fullName>Delivered_2_Hub</fullName>
        <active>true</active>
        <label>Ontvangen</label>
    </recordTypes>
    <recordTypes>
        <fullName>Delivered_2_Project</fullName>
        <active>true</active>
        <label>Afleveren</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LocationUtil.cls
public with sharing class LocationUtil {
    public static void entry(TriggerParams triggerParams) {
        List<Location__c> triggerNew = (List<Location__c>)triggerParams.triggerNew;
        List<Location__c> triggerOld = (List<Location__c>)triggerParams.triggerOld;
        Map<Id, Location__c> oldMap = (Map<Id, Location__c>)triggerParams.oldMap;
        Map<Id, Location__c> newMap = (Map<Id, Location__c>)triggerParams.newMap;

      
        
        if (triggerParams.isAfter){
          if (triggerParams.isUpdate || triggerParams.isInsert) {
            updateParentLocations(triggerNew);
            shareToForceUsers(newMap);
          }

          if (triggerParams.isUpdate) {
            recalculateLocationsCount(triggerNew, oldMap);
          }
          if (triggerParams.isDelete) {
            updateParentLocations(triggerOld);
            Set <Id> parentLocationIds = new Set <Id>();
            for (Location__c loc: triggerOld) {
                if (loc.Parent_Location__c != null) {
                    parentLocationIds.add(loc.Parent_Location__c);
                }
            }
          updateParentLocationsNoChild(parentLocationIds);

          }
        }
    }
    public static void shareToForceUsers (Map <Id, Location__c> locById){
        List <Location__c> tickets = [select Id, Hub_Building_Site__r.Project__r.Account__c , OwnerId, Hub_Building_Site__c 
                                            from Location__c where id in: locById.keySet() ];
        Set <Id> hubIds = new Set <Id>();
        for (Location__c loc: tickets) {
            hubIds.add(loc.Hub_building_Site__c);
        }                                   
        List <AccountHUb__c> accHubs = [select Id, Account__c from AccountHub__c where Hub_Building_Site__c in: hubIds];
        Set <Id> accIds1 = new Set <Id>();
        for (AccountHub__c acH: accHubs){
            accIds1.add(acH.account__c);
        }
        Set <Id> accIds = new Set <Id>();
        for (Location__c t: tickets) {
            if (t.Hub_Building_Site__r.Project__r.Account__c != null) {
                accIds.add(t.Hub_Building_Site__r.Project__r.Account__c);
            }
        }
        accIds.addAll(accIds1);
        System.debug('accs '+ accIds);
        List <User> users = [select isActive, Id from User where AccountId__c in :accIds and isActive = true];
        Map <Id, User> userById = new Map <Id, User>(users);
        System.debug('users' + users.size() + ' '  + users);
        List <Location__Share> sharingTicket = [SELECT  ParentId, Id, UserOrGroupId 
                                                FROM Location__Share where ParentId in: locById.keySet()  ];
        System.debug(sharingTicket.size() + ' ' + sharingTicket);
        Map <Id, Map<Id, Location__Share>> shareByUserByTicket = new Map <Id, Map<Id, Location__Share>>();
        for (Location__Share sh: sharingTicket) {
            if (shareByUserByTicket.containsKey(sh.ParentId)) {
                shareByUserByTicket.get(sh.ParentId).put(sh.UserOrGroupId, sh);
            } else {
                Map <Id, Location__Share> shByUser = new Map <Id, Location__Share>();
                shareByUserByTicket.put(sh.ParentId, shByUser);
            }
        }
        System.debug('shareByUserByTicket' + shareByUserByTicket.size() + ' '  + shareByUserByTicket);
        List <Location__Share> newSharings = new List <Location__Share>();
        for (Location__c t: tickets) {
            for (User u: users) {
                System.debug('shareByUserByTicket.get(t.id)' + shareByUserByTicket.get(t.id) + ' ' + u.id);
                if (!shareByUserByTicket.get(t.id).containsKey(u.Id) && t.OwnerId != u.id && u.isActive) {
                    newSharings.add(new Location__Share(ParentId = t.id, UserOrGroupId = u.Id, AccessLevel = 'Read'));
                }
            }
        }
        System.debug('add sharings ' + newSharings.size() + ' ' + newSharings);
        insert newSharings;
    }
    
    public static void updateParentLocations(List <Location__c> locations) {
        Set <Id> parentLocationIds = new Set <Id>();
        for (Location__c loc: locations) {
            if (loc.Parent_Location__c != null) {
                parentLocationIds.add(loc.Parent_Location__c);
            }
        }
        Map <Id, Location__c> parentLocations = new Map <Id, Location__c>([Select Id from Location__c where id in: parentLocationIds]);
        List<WWW_Detail__c> wwwDs = [SELECT Id, RecordType.DeveloperName, Location__c, Number_Of_Items__c FROM WWW_Detail__c 
                                    where (RecordType.DeveloperName = 'Delivered_2_Hub' OR RecordType.DeveloperName = 'Delivered_2_Project')
                                            and Location__c in :parentLocationIds and IsDeleted = false];

        Map<Id, List<WWW_Detail__c>> delToHubByLocationId = new Map<Id, List<WWW_Detail__c>>();
        Map<Id, List<WWW_Detail__c>> delToProjectByLocationId = new Map<Id, List<WWW_Detail__c>>();
        if( wwwDs != null && !wwwDs.isEmpty() ) {
            for(WWW_Detail__c wwwD : wwwDs) {
                if( wwwD.RecordType.DeveloperName == 'Delivered_2_Hub' ) {
                    if( delToHubByLocationId.get(wwwD.Location__c) == null ) {
                        delToHubByLocationId.put(wwwD.Location__c, new List<WWW_Detail__c>());
                    }
                    delToHubByLocationId.get(wwwD.Location__c).add(wwwD);
                }

                if( wwwD.RecordType.DeveloperName == 'Delivered_2_Project' ) {
                    if( delToProjectByLocationId.get(wwwD.Location__c) == null ) {
                        delToProjectByLocationId.put(wwwD.Location__c, new List<WWW_Detail__c>());
                    }
                    delToProjectByLocationId.get(wwwD.Location__c).add(wwwD);
                }
            }
        }

        for(Location__c parent: parentLocations.values()) {
            parent.Current_amount__c = 0;
            if( delToHubByLocationId.get(parent.Id) != null ) {
                for(WWW_Detail__c wwwD : delToHubByLocationId.get(parent.Id) ) {
                    parent.Current_amount__c += wwwD.Number_Of_Items__c;
                }
            }

            parent.Available_amount__c = 0;
            if( delToProjectByLocationId.get(parent.Id) != null ) {
                for(WWW_Detail__c wwwD : delToProjectByLocationId.get(parent.Id) ) {
                    parent.Available_amount__c += wwwD.Number_Of_Items__c;
                }
            }
        }

        System.debug('parentLocations ' + parentLocations.size() + ' ' + parentLocations);
        update parentLocations.values();
        //List <Location__c> childLocations = [select Id, Current_amount__c, Available_amount__c , Parent_Location__c from Location__c where Parent_Location__c in: parentLocationIds];
        //Map <Id, Decimal> sumByParentId = new Map <Id, Decimal>();
        //Map <Id, Decimal> sumRedByParentId = new Map <Id, Decimal>();
        //for (Location__c loc: childLocations) {
        //    if (loc.Current_amount__c == null) {
        //        loc.Current_amount__c = 0;
        //    }
        //    if (sumByParentId.containsKey(loc.Parent_Location__c)) {
        //        if (loc.Current_amount__c != null) {
        //            sumByParentId.put(loc.Parent_Location__c, sumByParentId.get(loc.Parent_Location__c)+loc.Current_amount__c);
        //        }
        //    } else {
        //         if (loc.Current_amount__c != null) {
        //            sumByParentId.put(loc.Parent_Location__c, loc.Current_amount__c);
        //            }
        //    }
        //    if (sumRedByParentId.containsKey(loc.Parent_Location__c)) {
        //        if (loc.Available_amount__c != null) {
        //            sumRedByParentId.put(loc.Parent_Location__c, sumRedByParentId.get(loc.Parent_Location__c)+loc.Available_amount__c);
        //        }
        //    } else {
        //        if (loc.Available_amount__c != null) {
        //            sumRedByParentId.put(loc.Parent_Location__c, loc.Available_amount__c);
        //        }
        //    }
        //}
        //for (Location__c parent: parentLocations.values()) {
        //    if (sumByParentId.containsKey(parent.Id)) {
        //        parent.Current_amount__c = sumByParentId.get(parent.Id);
        //        parent.Available_amount__c = sumRedByParentId.get(parent.id);
        //    }

        //}
        //System.debug('parentLocations ' + parentLocations.size() + ' ' + parentLocations);
        //update parentLocations.values();

    }

    public static void recalculateLocationsCount(List<Location__c> triggerNew, Map<Id, Location__c> oldMap)
    {
        Set<Id> locationIdsTorecalculate = new Set<Id>();
        List<Location__c> locationsToRecalculate = new List<Location__c>();

        for(Location__c loc : triggerNew)
        {
            Location__c oldLoc = oldMap.get(loc.Id);
            if( oldLoc != null )
            {
                if( oldLoc.Occupied__c != loc.Occupied__c )
                {
                    locationIdsTorecalculate.add(loc.Id);
                    locationsToRecalculate.add(loc);
                }
            }
        }

        List<SublocationDetail__c> subLocDetails = [Select Id, Name, Location__c, Location__r.Occupied__c, Location__r.Parent_Location__c, WWW_Detail__c from SublocationDetail__c 
                                                            where Location__c in :locationIdsTorecalculate];

        SubLocationDetailUtil.calculateSublocationsForProject(subLocDetails);
    }

    @future
    public static void updateParentLocationsNoChild (Set <Id> locations) {
        Map <Id, Location__c> parentLocations = new Map <Id, Location__c>([Select Id, Name, Current_amount__c from Location__c where id in: locations]);
        List <Location__c> childLocations =  new List <Location__c>([select Id, Name, Current_amount__c, Available_amount__c , Parent_Location__c from Location__c where Parent_Location__c in: locations]);
        List <Location__c> toUpdate = new List<Location__c>();
        List <Id> toSkipIds = new List<Id>();
        for(Location__c loc : childLocations){
            if(loc.Parent_Location__c != null){
                toSkipIds.add(loc.Parent_Location__c);
            }
        }
        Map <Id, Location__c> toSkip = new Map <Id, Location__c>([Select Id, Name, Current_amount__c from Location__c where id in: toSkipIds]);
        for(Id skip : toSkip.keySet()){
            if(parentLocations.containsKey(skip)){
                parentLocations.remove(skip);
            }
        }
        for(Location__c loc2Up : parentLocations.values()){

            loc2Up.Current_amount__c = null;
            toUpdate.add(loc2Up);
        }
        update toUpdate;
    }

}