src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Id__c</fullName>
        <formula>CASESAFEID(Id)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Id_</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Building_Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Help Text Hub/Building Site</inlineHelpText>
        <label>Hub/Building Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Hub_Building_Site__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Building Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requestor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requestor</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bouwticket</label>
    <nameField>
        <displayFormat>BT-{00000}</displayFormat>
        <label>Naam van Building Ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bouwticket</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Hub_Building_Site__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Building Sites</relationshipLabel>
        <relationshipName>Hubs_Building_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projecten__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (klant)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Projectcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projecten</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/UniqueNumber__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Number__c</fullName>
        <label>Number</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>UniqueNumber</label>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BuildingTicketUtil.cls
public without sharing class BuildingTicketUtil {
    public BuildingTicketUtil() {
        
    }
    public static void entry(TriggerParams triggerParams) {
        List<Building_Ticket__c> triggerNew = (List<Building_Ticket__c>)triggerParams.triggerNew;
        List<Building_Ticket__c> triggerOld = (List<Building_Ticket__c>)triggerParams.triggerOld;
        Map<Id, Building_Ticket__c> oldMap = (Map<Id, Building_Ticket__c>)triggerParams.oldMap;
        Map<Id, Building_Ticket__c> newMap = (Map<Id, Building_Ticket__c>)triggerParams.newMap;


        if (triggerParams.isBefore){
            if ( triggerParams.isInsert) {
                setName(triggerNew);
            }
        } else if (triggerParams.isAfter ){
            if (triggerParams.isUpdate || triggerParams.isInsert) {
                shareToForceUsers(newMap);
            }
        }
    }
    public static void setName (List <Building_Ticket__c> tickets) {
        List <UniqueNumber__c> uniqueNumbers = [select Name, Number__c from UniqueNumber__c];
        if (uniqueNumbers.size() == 0) {
            UniqueNumber__c unForToday = new UniqueNumber__c();
            unForToday.Name = String.valueOf(date.today().year()+'-'+date.today().month()+'-'+date.today().day());
            unForToday.Number__c = '1';
            insert unForToday;
        } else {
            if (uniqueNumbers.get(0).Name == String.valueOf(date.today().year()+'-'+date.today().month()+'-'+date.today().day())) {
                uniqueNumbers.get(0).Number__c = String.valueOf(Integer.valueOf(uniqueNumbers.get(0).Number__c) + 1);
                
            } else {
                uniqueNumbers.get(0).Number__c = '1';
                uniqueNumbers.get(0).Name = String.valueOf(date.today().year()+'-'+date.today().month()+'-'+date.today().day());
            }
            update uniqueNumbers;
        }
        uniqueNumbers = [select Name, Number__c from UniqueNumber__c];
        Set <Id> hubsIds = new Set <Id>();
        for (Building_Ticket__c ticket : tickets) {
            hubsIds.add(ticket.Hub_Building_Site__c);
        }
        Map <Id, Hub_Building_Site__c> hubsById = new Map <Id, Hub_Building_Site__c>([select Id, Name from Hub_Building_Site__c where id in: hubsIds]);
        
        for (Building_Ticket__c ticket : tickets) {
            ticket.Requestor__c = UserInfo.getUserId();
            //ticket.Name = hubsById.get(ticket.Hub_Building_Site__c).Name;
            
            //ticket.Name += ', '+uniqueNumbers.get(0).Number__c;
            //System.debug(ticket.Name);
        }
    }
    public static void shareToForceUsers (Map <Id, Building_Ticket__c> ticketsById){
        List <Building_Ticket__c> tickets = [select Id, Hub_Building_Site__r.Project__r.Account__c , OwnerId, Account__r.Id__c, Account__c 
                                            from Building_Ticket__c where id in: ticketsById.keySet() ];
        Set <Id> accIds = new Set <Id>();
        for (Building_Ticket__c t: tickets) {
            if (t.Hub_Building_Site__r.Project__r.Account__c != null){
                accIds.add(t.Hub_Building_Site__r.Project__r.Account__c);
            }

            if (t.Account__c != null){
                accIds.add(t.Account__r.Id__c);
            }
        }
        System.debug('accs '+ accIds);
        List <User> users = [select Id from User where AccountId__c in :accIds and IsActive = true];
        System.debug('users' + users.size() + ' '  + users);
        List <Building_Ticket__Share> sharingTicket = [SELECT  ParentId, Id, UserOrGroupId 
                                                FROM Building_Ticket__Share where ParentId in: ticketsById.keySet()  ];
        System.debug(sharingTicket.size() + ' ' + sharingTicket);
        Map <Id, Map<Id, Building_Ticket__Share>> shareByUserByTicket = new Map <Id, Map<Id, Building_Ticket__Share>>();
        for (Building_Ticket__Share sh: sharingTicket) {
            if (shareByUserByTicket.containsKey(sh.ParentId)) {
                shareByUserByTicket.get(sh.ParentId).put(sh.UserOrGroupId, sh);
            } else {
                Map <Id, Building_Ticket__Share> shByUser = new Map <Id, Building_Ticket__Share>();
                shareByUserByTicket.put(sh.ParentId, shByUser);
            }
        }
        System.debug('shareByUserByTicket' + shareByUserByTicket.size() + ' '  + shareByUserByTicket);
        List <Building_Ticket__Share> newSharings = new List <Building_Ticket__Share>();
        for (Building_Ticket__c t: tickets) {
            for (User u: users) {
                System.debug('shareByUserByTicket.get(t.id)' + shareByUserByTicket.get(t.id) + ' ' + u.id);
                if (!shareByUserByTicket.get(t.id).containsKey(u.Id) && t.OwnerId != u.id) {
                    newSharings.add(new Building_Ticket__Share(ParentId = t.id, UserOrGroupId = u.Id, AccessLevel = 'Edit'));
                }
            }
        }
        System.debug('add sharings ' + newSharings.size() + ' ' + newSharings);
        insert newSharings;
    }
}