src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SF_ID__c</fullName>
        <externalId>true</externalId>
        <label>SF_ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Building_Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Arrival_Time__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <description>Delivery Date</description>
        <inlineHelpText>Delivery Date</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description_Of_Activity__c</fullName>
        <label>Description Of Activity</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description_Of_Delivery__c</fullName>
        <label>Description Of Delivery</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Point__c</fullName>
        <label>End Point</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Gate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Help Text Gate</inlineHelpText>
        <label>Gate</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Gate</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Building_Tickets2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Help Text Hub/Building Site</inlineHelpText>
        <label>Hub/Building Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Hub_Building_Site__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Building Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loading_And_Unloading_Time__c</fullName>
        <inlineHelpText>Voer hier de tijd in die het kost om de lading te lossen in minuten</inlineHelpText>
        <label>Loading And Unloading Time (in minutes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loading_Unloading_Time_hours__c</fullName>
        <description>Set hours</description>
        <inlineHelpText>Set hours</inlineHelpText>
        <label>Loading_Unloading_Time_hours</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Site Location</value>
            </filterItems>
            <filterItems>
                <field>$Source.Hub_Building_Site__c</field>
                <operation>equals</operation>
                <valueField>Location__c.Hub_Building_Site__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projectmember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projectmember</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Projectmember__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Projectmember__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transporteur__c</fullName>
        <label>Transporteur</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vertical_Transport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Kies hier het verticale transport wat er nodig is om de levering te kunnen afleveren.</inlineHelpText>
        <label>Vertical Transport</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Vertical Transport</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Building_Tickets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bouwticket</label>
    <nameField>
        <displayFormat>BT-{00000}</displayFormat>
        <label>Naam van Building Ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bouwticket</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Hub_Building_Site__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description_Hub__c</fullName>
        <label>Description Hub</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Postalcode__c</fullName>
        <label>Postalcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Building Sites</relationshipLabel>
        <relationshipName>Hubs_Building_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SF_ID__c</fullName>
        <externalId>true</externalId>
        <label>SF_ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <recordTypes>
        <fullName>Hub</fullName>
        <active>true</active>
        <label>Hub</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Activity_Description__c</fullName>
        <label>Activity Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Box_Number__c</fullName>
        <label>Box Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Depth__c</fullName>
        <inlineHelpText>Diepte van het schap in CM. Dus met 2 decimalen voor milimeters</inlineHelpText>
        <label>Depth</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>M2_Height__c</fullName>
        <inlineHelpText>De hoogte met 2 decimalen</inlineHelpText>
        <label>Height</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Weight_p_m2__c</fullName>
        <inlineHelpText>Het maximale gewicht pet m2 met 2 decimalen</inlineHelpText>
        <label>Max Weight p/m2</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pallet_Place__c</fullName>
        <label>Pallet Place</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_ID__c</fullName>
        <externalId>true</externalId>
        <label>SF_ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <label>Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shelving_Subdivision__c</fullName>
        <label>Shelving (Subdivision)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Warehouse__c</fullName>
        <label>Warehouse</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Width__c</fullName>
        <inlineHelpText>De breedte van het schap in cm met 2 decimalen voor de milimeters</inlineHelpText>
        <label>Width</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Locatie</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locaties</pluralLabel>
    <recordTypes>
        <fullName>Gate</fullName>
        <active>true</active>
        <label>Gate</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projectmember__c.object
<CustomObject>
    <fields>
        <fullName>Project_Member_Name__c</fullName>
        <formula>Contact__r.FirstName + &apos; &apos; +  Contact__r.LastName</formula>
        <label>Project Member Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Projectmembers</relationshipLabel>
        <relationshipName>Projectmembers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SF_ID__c</fullName>
        <externalId>true</externalId>
        <label>SF_ID</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Projectmember</label>
    <nameField>
        <label>Projectmember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projectmembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/CreateTicketExtension.cls
public with sharing class CreateTicketExtension {
    public ComponentData compData {get; set;}

    public Building_Ticket__c ticket {
        get {
            if (ticket == null) {
                ticket = new Building_Ticket__c();
            }
            return ticket;
        } set;
    }

    public Boolean forceUser {
        get {
            if (forceUser == null) {
                User user = [select Id, AccountId__c, Profile.Name from User where id =: UserInfo.getUserId()];
                if (user.Profile.Name == 'Bouwmanager' || user.Profile.Name == 'Bouwticket account') {
                    forceUser = true;
                    ticket.Account__c = user.AccountId__c;
                } else {
                    forceUser = false;
                }
            }
            return forceUser;
        } set;
    }

    @AuraEnabled
    public static String locationSelected {get; set;}
    public static String accountSelected {get; set;}
    @AuraEnabled
    public static String gateSelected {get; set;}
    @AuraEnabled
    public static String hubSelected {get; set;}
    @AuraEnabled
    public static String vTSelected {get; set;}
    @AuraEnabled
    public static String normalFormatDate {get; set;}
    @AuraEnabled
    public static String managerSelected {get; set;}
    public static String project {get; set;}
    @AuraEnabled
    public static String cloneFrom {get; set;}

    @AuraEnabled
    public static String dOfDelivery {get; set;}
    @AuraEnabled
    public static String dOfActivity {get; set;}
    

    public static Map<String, String> hubNameById {get; set;}

    public String errorMessageArrivTime {get; set;}
    public String errorMessageLAUTime {get; set;}
    public String errorMessageDelTime {get; set;}
    public String message {get; set;}
    public String lAuTimeHours {get; set;}
    public String lAuTime{get; set;}
    public String arrivalTimeHours{get; set;}
    public String arrivalTime{get; set;}
    public String destinatioId {get; set;}

    private ApexPages.StandardController contr;

    public CreateTicketExtension(ApexPages.StandardController controller) {
        this.contr = controller;
        compData = new ComponentData ();
        compData.hubSelected = hubSelected;
        hubSelected = ApexPages.currentPage().getParameters().get('hubSelected');

        cloneFrom = ApexPages.currentPage().getParameters().get('cloneFrom');
        compData.cloneFrom = cloneFrom;
    }

    public CreateTicketExtension() {
        compData = new ComponentData ();
        hubSelected = ApexPages.currentPage().getParameters().get('hubSelected');
        compData.hubSelected = hubSelected;
    }

    public PageReference step2() {
        return new PageReference('/apex/CreateTicket?hubSelected=' + hubSelected);
    }

    public void getComponentData() {
        compData = new ComponentData ();
        compData.hubSelected = hubSelected;
        compData.cloneFrom = cloneFrom;


        if (cloneFrom != null) {
            cloneTicket(cloneFrom);
        }
    }

    public void setInfo() {
        ticket.Hub_Building_Site__c = hubSelected;
        if (ApexPages.currentPage().getParameters().get('deliveryTime') != '') {
            ticket.Delivery_Date__c =  Date.valueOf(ApexPages.currentPage().getParameters().get('deliveryTime'));
            normalFormatDate = String.valueOf(ticket.Delivery_Date__c.year()+'-'+ticket.Delivery_Date__c.month()+'-'+ticket.Delivery_Date__c.day());
        }
        compData.dateSelected = normalFormatDate;
    }

    public PageReference customReturn() {
        PageReference cancel = contr.cancel();
        return cancel;
    }

    public PageReference saveTicket() {
        message = 'This field is required';

        ticket.Gate__c = gateSelected;
        ticket.Location__c = locationSelected;
        ticket.Hub_Building_Site__c = hubSelected;
        ticket.Vertical_transport__c = vTSelected;
        ticket.Projectmember__c = managerSelected;
        ticket.Project__c = project;
        ticket.Destination__c = destinatioId;

        if (ApexPages.currentPage().getParameters().get('deliveryTime') != '') {
            ticket.Delivery_Date__c =  Date.valueOf(ApexPages.currentPage().getParameters().get('deliveryTime'));
        } else {
            errorMessageDelTime = message;
            return null;
        }

        if (arrivalTime != null && arrivalTimeHours != null) {
            ticket.Arrival_Time__c = Datetime.newInstance(ticket.Delivery_Date__c.year(), ticket.Delivery_Date__c.month(),
                        ticket.Delivery_Date__c.day(), Integer.valueOf(arrivalTimeHours), Integer.valueOf(arrivalTime), 0);
        } else {
            errorMessageArrivTime = message;
            return null;
        }

        if (arrivalTime == '0' && arrivalTimeHours == '0') {
            errorMessageArrivTime = message;
            return null;
        }

        if (lAuTime != null) {
            Decimal hours = 0;
            if (lAuTimeHours  != null) {
                hours = Decimal.valueOf(lAuTimeHours);
            }

            Decimal minutes = 0;
            if (lAuTime != null) {
                minutes = Decimal.valueOf(lAuTime );
            }

            ticket.Loading_And_Unloading_Time__c = hours * 60 + minutes;
        } else {
            errorMessageLAUTime = message;
            return null;
        }

        if (lAuTime == '0' && lAuTimeHours == '0') {
            errorMessageLAUTime = message;
            return null;
        }

        ticket.End_Point__c = ApexPages.currentPage().getParameters().get('endPoint');
        ticket.Description_Of_Delivery__c =  ApexPages.currentPage().getParameters().get('descrOfDelivery');
        ticket.Description_Of_Activity__c =  ApexPages.currentPage().getParameters().get('descrOfActivity');

        try{
            insert ticket;
            return new PageReference('/' + ticket.id);
        } catch(Exception e) {
            System.debug(e.getMessage());
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,'Error.'+e.getMessage() );
            ApexPages.addMessage(myMsg);
            return null;
        }

        return null;
    }

    public void cloneTicket(String clFrom){
        Set<Id> ticketId = new Set<Id>();
        ticketId.add(clFrom);

        Building_Ticket__c buildingTicketToClone = [SELECT Id, Account__c, Location__c, Hub_Building_Site__c, Gate__c, Vertical_transport__c, Projectmember__c, Destination__c,
                                                            Self_solving__c, Project__c, Delivery_Date__c, Arrival_Time__c, Loading_Unloading_Time_hours__c,
                                                            Loading_And_Unloading_Time__c, Transporteur__c, Description_Of_Activity__c, Description_Of_Delivery__c, End_Point__c
                                                        FROM Building_Ticket__c
                                                        WHERE Id IN: ticketId limit 1];

        if (null != buildingTicketToClone) {
            ticket = buildingTicketToClone.clone(false, true, false, false);

            getHubs();
            //getManagers();
            getGates();
            getDestinations();

            hubSelected = ticket.Hub_Building_Site__c;
            gateSelected = ticket.Gate__c;
            locationSelected = ticket.Location__c;
            vTSelected = ticket.Vertical_transport__c;
            managerSelected = ticket.Projectmember__c;
            destinatioId = ticket.Destination__c;
            System.debug('OBDEB managerSelected -->> ' + managerSelected);

            project = ticket.Project__c;

            dOfDelivery = ticket.Description_Of_Delivery__c;
            dOfActivity = ticket.Description_Of_Activity__c;

            /*was commented*/
            //Decimal tmpHours = ticket.Loading_And_Unloading_Time__c / 60;
            //lAuTimeHours = String.valueOf(tmpHours.intValue());

            //Decimal tmpMinutes = (tmpHours - tmpHours.round(System.RoundingMode.FLOOR)) * 60;
            //lAuTime = String.valueOf(tmpMinutes.intValue());
            /*was commented*/

            Datetime dt = ticket.Arrival_Time__c;
            arrivalTimeHours = String.valueOf(dt.hour());
            arrivalTime = String.valueOf(dt.minute());
        }
    }

    public static List<SelectOption> getLocations() {
        hubSelected = ApexPages.currentPage().getParameters().get('hubSelected');

        List<SelectOption> options = new List<SelectOption>();
        List<Location__c> locations = new List<Location__c>();

        locations = [SELECT Activity_Description__c, Box_Number__c, CreatedById, CreatedDate, IsDeleted, Depth__c,
                                M2_Height__c, Hub_Building_Site__c, LastActivityDate, LastModifiedById, LastModifiedDate,
                                Level__c, Name, Max_Weight_p_m2__c, OwnerId, Pallet_Place__c, Id, RecordTypeId, SF_ID__c,
                                Section__c, Shelving_Subdivision__c, SystemModstamp, Warehouse__c, Width__c
                            FROM Location__c
                            where RecordType.Name = 'Site Location' and Hub_Building_Site__c = :hubSelected];

        options.add(new SelectOption('', ''));
        for (Location__c loc : locations) {
            options.add(new SelectOption(loc.id, loc.Name));
        }

        return options;
    }

    public static List<SelectOption> getManagers() {
        //managerSelected = ApexPages.currentPage().getParameters().get('managerSelected');
        //System.debug('248 OBDEB managerSelected -->> ' + managerSelected);

        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', ''));

        Hub_Building_Site__c buildSite = [Select Project__c from Hub_Building_Site__c where id=: hubSelected];
        project = buildSite.Project__c;

        List <Projectmember__c> managers = [SELECT Id, Project_Member_Name__c
                                            FROM  Projectmember__c
                                            Where  Project__c =: buildSite.Project__c];

        for (Projectmember__c manager : managers) {
            options.add(new SelectOption(manager.id, manager.Project_Member_Name__c));
        }

        return options;
    }

    public static List<SelectOption> getAccounts() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', ''));

        List <Account> accounts = [select Id, Name from Account];
        for (Account acc : accounts) {
            options.add(new SelectOption(acc.id, acc.Name));
        }

        return options;
    }

    public static List<SelectOption> getGates() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', ''));

        hubSelected = ApexPages.currentPage().getParameters().get('hubSelected');

        List <Location__c> locations = [SELECT Activity_Description__c, Box_Number__c, CreatedById, CreatedDate, IsDeleted, Depth__c,
                                            M2_Height__c, Hub_Building_Site__c, LastActivityDate, LastModifiedById, LastModifiedDate,
                                            Level__c, Name, Max_Weight_p_m2__c, OwnerId, Pallet_Place__c, Id, RecordTypeId, SF_ID__c,
                                            Section__c, Shelving_Subdivision__c, SystemModstamp, Warehouse__c, Width__c
                                        FROM Location__c
                                        where RecordType.Name = 'Gate' and Hub_Building_Site__c=:hubSelected];

        for (Location__c loc : locations) {
            options.add(new SelectOption(loc.id, loc.Name));
        }

        return options;
    }

    public static List<SelectOption> getHubs() {
        hubNameById = new Map<String, String>();
        hubSelected = ApexPages.currentPage().getParameters().get('hubSelected');

        List<SelectOption> options = new List<SelectOption>();

        List <Hub_Building_Site__c> hubs = [SELECT City__c, CreatedById, CreatedDate, IsDeleted, Description_Hub__c, Name, LastActivityDate,
                                                    LastModifiedById, LastModifiedDate, OwnerId, Postalcode__c, Id, RecordTypeId, SF_ID__c,
                                                    Street__c, SystemModstamp
                                            FROM Hub_Building_Site__c
                                            WHERE RecordType.Name = 'Building Site' ];
        for (Hub_Building_Site__c hub : hubs) {
            hubNameById.put(hub.id, hub.Name);
            options.add(new SelectOption(hub.id, hub.Name));
        }

        return options;
    }

    public static List<SelectOption> getVerticalTransports() {
        hubSelected = ApexPages.currentPage().getParameters().get('hubSelected');

        List<SelectOption> options = new List<SelectOption>();

        List <Location__c> locs = [SELECT Activity_Description__c, Box_Number__c, CreatedById, CreatedDate, IsDeleted, Depth__c,
                                            M2_Height__c, Hub_Building_Site__c, LastActivityDate, LastModifiedById, LastModifiedDate,
                                            Level__c, Name, Max_Weight_p_m2__c, OwnerId, Pallet_Place__c, Id, RecordTypeId, SF_ID__c,
                                            Section__c, Shelving_Subdivision__c, SystemModstamp, Warehouse__c, Width__c
                                        FROM Location__c
                                        where RecordType.Name = 'Vertical Transport' and Hub_Building_Site__c=:hubSelected];

        Map <Id, Location__c> locsById = new Map <Id, Location__c>(locs);
        // CHANGE BEFORE DEPLOY
        String parentId = ApexPages.currentPage().getParameters().get('CF00N8E000000HF5d_lkid');
        if ( parentId != null) {
            options.add(new SelectOption(parentId, locsById.get(parentId).Name));
        } else {
            options.add(new SelectOption('', ''));
        }

        for (Location__c loc : locs) {
            options.add(new SelectOption(loc.id, loc.Name));
        }

        return options;
    }

    public List<SelectOption> getMinutes() {
        List<SelectOption> options = new List<SelectOption>();

        for (Integer i =0; i< 60; i+=15) {
            if (i == 0) {
                options.add(new SelectOption(String.valueOf(i), '0' + String.valueOf(i)));
            } else {
                options.add(new SelectOption(String.valueOf(i), String.valueOf(i)));
            }
        }

        return options;
    }

    public List<SelectOption> getHours() {
        List<SelectOption> options = new List<SelectOption>();

        for (Integer i = 0; i < 24; i++) {
            String val = String.valueOf(i);
            if (String.valueOf(i).length() == 1) {
                val = '0' + String.valueOf(i);
            }

            options.add(new SelectOption(String.valueOf(i), val));
        }

        return options;
    }

    public List<SelectOption> getDestinations() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('', ''));

        List<Destination__c> destinationsList = [Select Id, Name from Destination__c where Hub_Building_Site__c = :hubSelected];
        if (destinationsList != null && !destinationsList.isEmpty()) {
            for(Destination__c dest : destinationsList) {
                options.add(new SelectOption(dest.Id, dest.Name));
            }
        }

        return options;
    }
}