src/objects/AccountHub__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AccountsHubs</relationshipLabel>
        <relationshipName>AccountsHubs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>AccountsHubs</relationshipLabel>
        <relationshipName>AccountsHubs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AccountHub</label>
    <nameField>
        <displayFormat>AH-{000000}</displayFormat>
        <label>AccountHub Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountsHubs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Building_Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Arrival_Time__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <description>Delivery Date</description>
        <inlineHelpText>Delivery Date</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Help Text Gate</inlineHelpText>
        <label>Gate</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Gate</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Building_Tickets2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Help Text Hub/Building Site</inlineHelpText>
        <label>Hub/Building Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Hub_Building_Site__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Building Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loading_And_Unloading_Time__c</fullName>
        <inlineHelpText>Voer hier de tijd in die het kost om de lading te lossen in minuten</inlineHelpText>
        <label>Loading And Unloading Time (in minutes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Site Location</value>
            </filterItems>
            <filterItems>
                <field>$Source.Hub_Building_Site__c</field>
                <operation>equals</operation>
                <valueField>Location__c.Hub_Building_Site__r.Id</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projectmember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projectmember</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Projectmember__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Projectmember__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <label>UserId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vertical_Transport__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Kies hier het verticale transport wat er nodig is om de levering te kunnen afleveren.</inlineHelpText>
        <label>Vertical Transport</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Location__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Vertical Transport</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Building_Tickets1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bouwticket</label>
    <nameField>
        <displayFormat>BT-{00000}</displayFormat>
        <label>Naam van Building Ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bouwticket</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Hub_Building_Site__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Building Sites</relationshipLabel>
        <relationshipName>Hubs_Building_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Locatie</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locaties</pluralLabel>
    <recordTypes>
        <fullName>Gate</fullName>
        <active>true</active>
        <label>Gate</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projecten__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (klant)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Projectcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projecten</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projectmember__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Projectmembers</relationshipLabel>
        <relationshipName>Projectmembers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Projectmember</label>
    <nameField>
        <label>Projectmember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projectmembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CreateTicketAndCallendarTest.cls
@isTest
private class CreateTicketAndCallendarTest {
    @isTest static void test_createTicket(){
        TestDataGenerator.fillTriggerSwitcherValues();

        Account account = TestDataGenerator.createBouwticketAccount('testAccount');
        Contact contact = TestDataGenerator.createTestContact(account);

        User user;
        Test.startTest();
            user = TestDataGenerator.createTestBouwticketUser(account);
        Test.stopTest();

        Projecten__c project = TestDataGenerator.createTestProject(account, 'testestest');
        Projectmember__c member = TestDataGenerator.createTestProjectMember(project, contact);
        Hub_Building_Site__c buldingSite = TestDataGenerator.createTestHubBuildingSite('Test Building Site', project);
        Location__c gate = TestDataGenerator.createTestGateLocation('TestGate');
        Location__c siteL = TestDataGenerator.createTestSiteLocation(buldingSite, 'Test Site Location');
        Location__c verTr = TestDataGenerator.createTestVerticalTransport('Test Vertical Transport');

        ApexPages.StandardController st = new ApexPages.StandardController (new Building_Ticket__c());
        CreateTicketExtension ct = new CreateTicketExtension();
        CreateTicketExtension ctrl = new CreateTicketExtension(st);

        CreateTicketExtension.getGates();
        CreateTicketExtension.getHubs();
        CreateTicketExtension.getLocations();

        List<SelectOption> minutes = ct.getMinutes();
        List<SelectOption> hours = ct.getHours();
        List<SelectOption> accs = CreateTicketExtension.getAccounts();
        System.runAs(user) {
            Boolean forceUser = ct.forceUser;
        }

        ctrl.getComponentData();

        CreateTicketExtension.getVerticalTransports();
        CreateTicketExtension.gateSelected = gate.id;
        CreateTicketExtension.hubSelected = buldingSite.id;
        CreateTicketExtension.getManagers() ;
        CreateTicketExtension.locationSelected = siteL.id;
        CreateTicketExtension.vTSelected = verTr.id;
        CalendarComponentController calendatCtrl = new CalendarComponentController();
        calendatCtrl.componentData = new ComponentData();
        calendatCtrl.componentData.hubSelected = buldingSite.id;
        calendatCtrl.componentData.dateSelected = '2015-12-25';
        calendatCtrl.getJsonForCalendar();

        Test.setCurrentPageReference(Page.CreateTicket);
        System.currentPageReference().getParameters().put('deliveryTime', '2015-12-25');
        System.currentPageReference().getParameters().put('arrivalTime', '30');
        System.currentPageReference().getParameters().put('lAuTime', '45');
        System.currentPageReference().getParameters().put('arrivalTimeHours', '1');
        System.currentPageReference().getParameters().put('lAuTimeHours', '0');
        System.currentPageReference().getParameters().put('managerSelected', member.id);

        ctrl.lAuTimeHours = '1';
        ctrl.lAuTime = '15';
        ctrl.arrivalTimeHours = '1';
        ctrl.arrivalTime = '15';
        ctrl.setInfo();
        ctrl.saveTicket();

        Test.setCurrentPageReference(Page.Calendar);
        Building_Ticket__c t = new Building_Ticket__c(Gate__c = gate.id , Hub_Building_Site__c = buldingSite.id, Location__c = siteL.id, Projectmember__c = member.id,
                        Vertical_Transport__c = verTr.id, Project__c = project.id, Arrival_Time__c = datetime.now(), Delivery_Date__c = Date.today(), Loading_And_Unloading_Time__c = 45,  Account__c = account.id );
        insert t;

        List<Building_Ticket__c> tickets = [select Id from Building_Ticket__c limit 1];
        System.assertEquals(1, tickets.size());

        st = new ApexPages.StandardController(tickets.get(0));

        CalendarExtension ctrl1 = new CalendarExtension(st);
        CalendarComponentController ctrl2 = new CalendarComponentController();

        ctrl2.componentData = new ComponentData();
        ctrl2.componentData.hubSelected = buldingSite.id;
        ctrl2.componentData.dateSelected = '2015-12-25';
        ctrl2.getJsonForCalendar();
        ctrl2.leftIds.add(verTr.id);
        ctrl2.getJsonForCalendar();
        ctrl2.change();
        ctrl2.getbodyForTable();

        /**/
        String count = ctrl2.count;
        /**/
        tickets.get(0).Status__c = 'Assigned';
        update tickets;

        tickets = [select Id, UserId__c from Building_Ticket__c];
        System.assertNotEquals(null, tickets.get(0).UserId__c);

        TicketPDFExtension pdfCtrl = new TicketPDFExtension();
        pdfCtrl.ticketRecord = tickets.get(0);
        pdfCtrl.showPrintButton = '1';

        Boolean init = pdfCtrl.getInit();

        Hub_Building_Site__c buldingSite1 = TestDataGenerator.createTestHubBuildingSite('Test Building Site', null);

        AccountHub__c acH = new AccountHub__c(Account__c = account.id, Hub_Building_Site__c = buldingSite1.Id );
        insert acH;

        System.assertEquals(1, [SELECT  AccountId, Id, UserOrGroupId 
                                                FROM AccountShare where UserOrGroupId =: user.id].size());
        System.assertEquals(2, [SELECT   UserOrGroupId 
                                                FROM Hub_Building_site__Share where UserOrGroupId =: user.id].size());
        System.assertEquals(1, [SELECT   UserOrGroupId 
                                                FROM Location__Share where UserOrGroupId =: user.id].size());
        System.assertEquals(2, [SELECT   UserOrGroupId 
                                                FROM Building_Ticket__Share where UserOrGroupId =: user.id].size());
    }

    @isTest static void test_cloneTicket() {
        TestDataGenerator.fillTriggerSwitcherValues();

        Account account = TestDataGenerator.createBouwticketAccount('testAccount');
        Contact contact = TestDataGenerator.createTestContact(account);

        User user;
        Test.startTest();
            user = TestDataGenerator.createTestBouwticketUser(account);
        Test.stopTest();

        Projecten__c project = TestDataGenerator.createTestProject(account, 'testestest');
        Projectmember__c member = TestDataGenerator.createTestProjectMember(project, contact);
        Hub_Building_Site__c buldingSite = TestDataGenerator.createTestHubBuildingSite('Test Building Site', project);
        Location__c gate = TestDataGenerator.createTestGateLocation('TestGate');
        Location__c siteL = TestDataGenerator.createTestSiteLocation(buldingSite, 'Test Site Location');
        Location__c verTr = TestDataGenerator.createTestVerticalTransport('Test Vertical Transport');

        Building_Ticket__c t = new Building_Ticket__c(Gate__c = gate.id , Hub_Building_Site__c = buldingSite.id, Location__c = siteL.id, Projectmember__c = member.id,
                        Vertical_Transport__c = verTr.id, Project__c = project.id, Arrival_Time__c = datetime.now(), Delivery_Date__c = Date.today(), Loading_And_Unloading_Time__c = 45,  Account__c = account.id );
        insert t;

        PageReference pageRef = Page.CreateTicket;
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('hubSelected', buldingSite.id);
        ApexPages.currentPage().getParameters().put('cloneFrom', t.id);

        ApexPages.StandardController sc = new ApexPages.StandardController(new Building_Ticket__c());
        CreateTicketExtension ctrl = new CreateTicketExtension(sc);

        ctrl.getComponentData();

        ctrl.customReturn();
    }

    @isTest static void test_negativeDeliveryTime(){
        TestDataGenerator.fillTriggerSwitcherValues();

        Account account = TestDataGenerator.createBouwticketAccount('testAccount');
        Contact contact = TestDataGenerator.createTestContact(account);

        User user;
        Test.startTest();
            user = TestDataGenerator.createTestBouwticketUser(account);
        Test.stopTest();

        Projecten__c project = TestDataGenerator.createTestProject(account, 'testestest');
        Projectmember__c member = TestDataGenerator.createTestProjectMember(project, contact);
        Hub_Building_Site__c buldingSite = TestDataGenerator.createTestHubBuildingSite('Test Building Site', project);
        Location__c gate = TestDataGenerator.createTestGateLocation('TestGate');
        Location__c siteL = TestDataGenerator.createTestSiteLocation(buldingSite, 'Test Site Location');
        Location__c verTr = TestDataGenerator.createTestVerticalTransport('Test Vertical Transport');

        ApexPages.StandardController st = new ApexPages.StandardController (new Building_Ticket__c());
        CreateTicketExtension ct = new CreateTicketExtension();
        CreateTicketExtension ctrl = new CreateTicketExtension(st);

        CreateTicketExtension.getGates();
        CreateTicketExtension.getHubs();
        CreateTicketExtension.getLocations();

        List<SelectOption> minutes = ct.getMinutes();
        List<SelectOption> hours = ct.getHours();
        List<SelectOption> accs = CreateTicketExtension.getAccounts();
        System.runAs(user) {
            Boolean forceUser = ct.forceUser;
        }

        ctrl.getComponentData();

        CreateTicketExtension.getVerticalTransports();
        CreateTicketExtension.gateSelected = gate.id;
        CreateTicketExtension.hubSelected = buldingSite.id;
        CreateTicketExtension.getManagers() ;
        CreateTicketExtension.locationSelected = siteL.id;
        CreateTicketExtension.vTSelected = verTr.id;
        CalendarComponentController calendatCtrl = new CalendarComponentController();
        calendatCtrl.componentData = new ComponentData();
        calendatCtrl.componentData.hubSelected = buldingSite.id;
        calendatCtrl.componentData.dateSelected = '2015-12-25';
        calendatCtrl.getJsonForCalendar();

        Test.setCurrentPageReference(Page.CreateTicket);
        System.currentPageReference().getParameters().put('deliveryTime', '');
        System.currentPageReference().getParameters().put('hubSelected', buldingSite.id);
        System.currentPageReference().getParameters().put('arrivalTime', '30');
        System.currentPageReference().getParameters().put('lAuTime', '45');
        System.currentPageReference().getParameters().put('arrivalTimeHours', '1');
        System.currentPageReference().getParameters().put('lAuTimeHours', '0');
        System.currentPageReference().getParameters().put('managerSelected', member.id);

        ctrl.lAuTimeHours = '1';
        ctrl.lAuTime = '15';
        ctrl.arrivalTimeHours = '1';
        ctrl.arrivalTime = '15';
        ctrl.setInfo();
        ctrl.saveTicket();
    }

    @isTest static void test_negativeArrivalTime(){
        TestDataGenerator.fillTriggerSwitcherValues();

        Account account = TestDataGenerator.createBouwticketAccount('testAccount');
        Contact contact = TestDataGenerator.createTestContact(account);

        User user;
        Test.startTest();
            user = TestDataGenerator.createTestBouwticketUser(account);
        Test.stopTest();

        Projecten__c project = TestDataGenerator.createTestProject(account, 'testestest');
        Projectmember__c member = TestDataGenerator.createTestProjectMember(project, contact);
        Hub_Building_Site__c buldingSite = TestDataGenerator.createTestHubBuildingSite('Test Building Site', project);
        Location__c gate = TestDataGenerator.createTestGateLocation('TestGate');
        Location__c siteL = TestDataGenerator.createTestSiteLocation(buldingSite, 'Test Site Location');
        Location__c verTr = TestDataGenerator.createTestVerticalTransport('Test Vertical Transport');

        ApexPages.StandardController st = new ApexPages.StandardController (new Building_Ticket__c());
        CreateTicketExtension ct = new CreateTicketExtension();
        CreateTicketExtension ctrl = new CreateTicketExtension(st);

        CreateTicketExtension.getGates();
        CreateTicketExtension.getHubs();
        CreateTicketExtension.getLocations();

        List<SelectOption> minutes = ct.getMinutes();
        List<SelectOption> hours = ct.getHours();
        List<SelectOption> accs = CreateTicketExtension.getAccounts();
        System.runAs(user) {
            Boolean forceUser = ct.forceUser;
        }

        ctrl.getComponentData();

        CreateTicketExtension.getVerticalTransports();
        CreateTicketExtension.gateSelected = gate.id;
        CreateTicketExtension.hubSelected = buldingSite.id;
        CreateTicketExtension.getManagers() ;
        CreateTicketExtension.locationSelected = siteL.id;
        CreateTicketExtension.vTSelected = verTr.id;
        CalendarComponentController calendatCtrl = new CalendarComponentController();
        calendatCtrl.componentData = new ComponentData();
        calendatCtrl.componentData.hubSelected = buldingSite.id;
        calendatCtrl.componentData.dateSelected = '2015-12-25';
        calendatCtrl.getJsonForCalendar();

        Test.setCurrentPageReference(Page.CreateTicket);
        System.currentPageReference().getParameters().put('deliveryTime', '2015-12-25');
        System.currentPageReference().getParameters().put('hubSelected', buldingSite.id);
        System.currentPageReference().getParameters().put('arrivalTime', '');
        System.currentPageReference().getParameters().put('lAuTime', '45');
        System.currentPageReference().getParameters().put('arrivalTimeHours', '1');
        System.currentPageReference().getParameters().put('lAuTimeHours', '0');
        System.currentPageReference().getParameters().put('managerSelected', member.id);

        ctrl.lAuTimeHours = '1';
        ctrl.lAuTime = '15';
        ctrl.arrivalTimeHours = '1';
        ctrl.arrivalTime = null;
        ctrl.setInfo();
        ctrl.saveTicket();

        ctrl.lAuTimeHours = '1';
        ctrl.lAuTime = '15';
        ctrl.arrivalTimeHours = '0';
        ctrl.arrivalTime = '0';
        ctrl.setInfo();
        ctrl.saveTicket();
    }

    @isTest static void test_negativeDurationTime(){
        TestDataGenerator.fillTriggerSwitcherValues();

        Account account = TestDataGenerator.createBouwticketAccount('testAccount');
        Contact contact = TestDataGenerator.createTestContact(account);

        User user;
        Test.startTest();
            user = TestDataGenerator.createTestBouwticketUser(account);
        Test.stopTest();

        Projecten__c project = TestDataGenerator.createTestProject(account, 'testestest');
        Projectmember__c member = TestDataGenerator.createTestProjectMember(project, contact);
        Hub_Building_Site__c buldingSite = TestDataGenerator.createTestHubBuildingSite('Test Building Site', project);
        Location__c gate = TestDataGenerator.createTestGateLocation('TestGate');
        Location__c siteL = TestDataGenerator.createTestSiteLocation(buldingSite, 'Test Site Location');
        Location__c verTr = TestDataGenerator.createTestVerticalTransport('Test Vertical Transport');

        ApexPages.StandardController st = new ApexPages.StandardController (new Building_Ticket__c());
        CreateTicketExtension ct = new CreateTicketExtension();
        CreateTicketExtension ctrl = new CreateTicketExtension(st);

        CreateTicketExtension.getGates();
        CreateTicketExtension.getHubs();
        CreateTicketExtension.getLocations();

        List<SelectOption> minutes = ct.getMinutes();
        List<SelectOption> hours = ct.getHours();
        List<SelectOption> accs = CreateTicketExtension.getAccounts();
        System.runAs(user) {
            Boolean forceUser = ct.forceUser;
        }

        ctrl.getComponentData();

        CreateTicketExtension.getVerticalTransports();
        CreateTicketExtension.gateSelected = gate.id;
        CreateTicketExtension.hubSelected = buldingSite.id;
        CreateTicketExtension.getManagers() ;
        CreateTicketExtension.locationSelected = siteL.id;
        CreateTicketExtension.vTSelected = verTr.id;
        CalendarComponentController calendatCtrl = new CalendarComponentController();
        calendatCtrl.componentData = new ComponentData();
        calendatCtrl.componentData.hubSelected = buldingSite.id;
        calendatCtrl.componentData.dateSelected = '2015-12-25';
        calendatCtrl.getJsonForCalendar();

        Test.setCurrentPageReference(Page.CreateTicket);
        System.currentPageReference().getParameters().put('deliveryTime', '2015-12-25');
        System.currentPageReference().getParameters().put('hubSelected', buldingSite.id);
        System.currentPageReference().getParameters().put('arrivalTime', '');
        System.currentPageReference().getParameters().put('lAuTime', '45');
        System.currentPageReference().getParameters().put('arrivalTimeHours', '1');
        System.currentPageReference().getParameters().put('lAuTimeHours', '0');
        System.currentPageReference().getParameters().put('managerSelected', member.id);

        ctrl.lAuTimeHours = '1';
        ctrl.lAuTime = null;
        ctrl.arrivalTimeHours = '1';
        ctrl.arrivalTime = '15';
        ctrl.setInfo();
        ctrl.saveTicket();

        ctrl.lAuTimeHours = '0';
        ctrl.lAuTime = '0';
        ctrl.arrivalTimeHours = '1';
        ctrl.arrivalTime = '15';
        ctrl.setInfo();
        ctrl.saveTicket();

        ctrl.step2();
    }
}