src/objects/ActiveTrigger__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>ActiveTrigger</label>
</CustomObject>

src/objects/Hub_Building_Site__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Building Sites</relationshipLabel>
        <relationshipName>Hubs_Building_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <recordTypes>
        <fullName>Hub</fullName>
        <active>true</active>
        <label>Hub</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Kind_Of_Packages__c</fullName>
        <inlineHelpText>Let op: de geselecteerde verpakking moet de eenheid zijn waarop het item afgeroepen gaat worden. Dus per stuk leveren is verpakking stuks of als de klant het per doos wil is de verpakking doos</inlineHelpText>
        <label>Kind Of Packages</label>
        <picklist>
            <picklistValues>
                <fullName>Balen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Big Bag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bok</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boxen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Container</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deellading vrachtwagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dozen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flessen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasbok Hout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasbok Staal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSA BAM Kar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haspels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kannen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kartons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kooikar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kratten</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los gestort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pakken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pallets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stuks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tanks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vaten</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volledige vrachtwagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zakken</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_Of_Units_Per_Package__c</fullName>
        <label>Number Of Units Per Package</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Sublocations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Locatie</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locaties</pluralLabel>
    <recordTypes>
        <fullName>Gate</fullName>
        <active>true</active>
        <label>Gate</label>
    </recordTypes>
    <recordTypes>
        <fullName>Hublocation</fullName>
        <active>true</active>
        <label>Hublocation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projecten__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (klant)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Projectcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projecten</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projectmember__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Projectmembers</relationshipLabel>
        <relationshipName>Projectmembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Projectmembers</relationshipLabel>
        <relationshipName>Projectmembers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Projectmember</label>
    <nameField>
        <label>Projectmember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projectmembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SublocationDetail__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>SublocationDetails</relationshipLabel>
        <relationshipName>SublocationDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_items__c</fullName>
        <formula>WWW_Detail__r.Number_Of_Items__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number of  items</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WWW_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>WWW-Detail</label>
        <referenceTo>WWW_Detail__c</referenceTo>
        <relationshipLabel>SublocationDetails</relationshipLabel>
        <relationshipName>SublocationDetails</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SublocationDetail</label>
    <nameField>
        <displayFormat>SD-{0000}</displayFormat>
        <label>SublocationDetail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SublocationDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/WWW__c.object
<CustomObject>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Projectmember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Aanvrager</description>
        <inlineHelpText>Dit invulveld is bedoeld om de aanvrager te benoemen.</inlineHelpText>
        <label>Aanvrager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Projectmember__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Projectmember__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WWW</label>
    <nameField>
        <displayFormat>WWW-{0}</displayFormat>
        <label>WWW Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WWW</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WWW_Detail__c.object
<CustomObject>
    <description>Who What Where
Wie Wat Waar</description>
    <fields>
        <fullName>Arrival_Truck_On_Hub__c</fullName>
        <label>Arrival Truck On Hub</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Damage_Package__c</fullName>
        <label>Damage Package</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Einddatum_opslag__c</fullName>
        <label>Einddatum opslag</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Kind_Of_Packages__c</fullName>
        <formula>TEXT(WWW__r.Item__r.Kind_Of_Packages__c)</formula>
        <label>Kind Of Packages</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Itemlocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_Of_Items__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Aantal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_Of_Units_Per_Package__c</fullName>
        <formula>WWW__r.Item__r.Number_Of_Units_Per_Package__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Number Of Units Per Package</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projectcode</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>WWW-Detail</relationshipLabel>
        <relationshipName>Itemlocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projectmember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projectmember</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Projectmember__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Projectmember__c</referenceTo>
        <relationshipName>Itemlocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>WWWD_sublocations__c</fullName>
        <label>WWWD sublocations</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WWW__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WWW</label>
        <referenceTo>WWW__c</referenceTo>
        <relationshipLabel>WWW-Detail (WWW)</relationshipLabel>
        <relationshipName>WWW_Detail1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WWW-Detail</label>
    <nameField>
        <displayFormat>WWW-D-{0}</displayFormat>
        <label>WWW Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WWW-Detail</pluralLabel>
    <recordTypes>
        <fullName>Delivered_2_Hub</fullName>
        <active>true</active>
        <label>Ontvangen</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataGenerator.cls
public with sharing class TestDataGenerator {
	public TestDataGenerator() {

	}

	public static void fillTriggerSwitcherValues() {
		Set<String> triggerNames = new Set<String>();
		triggerNames.add('AccountHubUtil');
		triggerNames.add('BuildingTicketUtil');
		triggerNames.add('HubUtil');
		triggerNames.add('LocationUtil');
		triggerNames.add('ProductUtil');
		triggerNames.add('ProjectUtil');
		triggerNames.add('SubLocationDetailUtil');
		triggerNames.add('UserUtil');
		triggerNames.add('WWWDetailUtil');

		List<ActiveTrigger__c> toInsert = new List<ActiveTrigger__c>();

		for (String str : triggerNames) {
			ActiveTrigger__c activeTrigger = new ActiveTrigger__c();
		    activeTrigger.Name = str;
		    activeTrigger.IsActive__c = true;

		    toInsert.add(activeTrigger);
		}

		insert toInsert;
	}

	public static void createTestWwwDetailOntvangen(WWW__c www, Location__c location, Decimal numberOfItems) {
		RecordType rcTp = [Select Id from RecordType where sObjectType = 'WWW_Detail__c' AND DeveloperName = 'Delivered_2_Hub' limit 1];

		WWW_Detail__c detail = new WWW_Detail__c();
		detail.WWW__c = www.Id;
		detail.RecordTypeId = rcTp.Id;
		detail.Number_Of_Items__c = numberOfItems;
		detail.Location__c = location.Id;
		detail.Damage_Package__c = 'No';
		detail.Arrival_Truck_On_Hub__c = DateTime.newInstance(2017, 4, 25, 8, 0, 0);
		detail.Einddatum_opslag__c = DateTime.newInstance(2017, 4, 30, 8, 0, 0);
		detail.WWWD_sublocations__c = location.Name + ' ABCD';

		insert detail;

		List<Location__c> subLocs = [select Id, Name from Location__c where Parent_Location__c = :location.Id];

		List<SubLocationDetail__c> sublocsToInsert = new List<SubLocationDetail__c>();
		for (Location__c loc : subLocs) {
			sublocsToInsert.add(new SubLocationDetail__c(WWW_detail__c = detail.id, Location__c = loc.Id));
		}

		insert sublocsToInsert;
	}

	public static User createTestBouwticketUser(Account acc) {
		Profile profile = [select Id from Profile where Name = 'Bouwticket account'];

        User user = new User();
        user.Username = 'contact@ukr.net';
        user.Email = 'contact@ukr.net';
        user.FirstName = 'contact';
        user.CommunityNickname = 'test65454';
        user.LastName = 'contact';
        user.ProfileId = profile.Id;
        user.isActive = true;
        user.Alias = 'contact' ;
        user.EmailEncodingKey='UTF-8';
        user.languageLocaleKey='en_US';
        user.LocaleSidKey='en_US';
        user.isActive = true;
        user.AccountId__c = acc.id;
        user.TimeZoneSidKey='Europe/Amsterdam';

        insert user;

        return user;
	}

	public static Account createBouwticketAccount(String accName) {
		RecordType accRT = [select Id, Name from RecordType where Name = 'Client'];

        Account acc = new Account (RecordTypeId = accRT.id, Name = accName);
        insert acc;

        return acc;
	}

	public static Item__c createTestItem(String itemName, Decimal itemsPerPackage) {
		Item__c item = new Item__c();
		item.Name = itemName;
		item.Kind_Of_Packages__c = 'Balen';
		item.Number_Of_Units_Per_Package__c = itemsPerPackage;

		insert item;

		return item;
	}

	public static Contact createTestContact(Account acc) {
		Contact cont = new Contact(AccountId = acc.id, LastName = 'Test');
        insert cont;

        return cont;
	}

	public static Projecten__c createTestProject(Account acc, String name) {
		Projecten__c pr = new Projecten__c(Account__c = acc.id, Name = name);
        insert pr;

		return pr;
	}

	public static Projectmember__c createTestProjectMember(Projecten__c proj, Contact cont) {
		Projectmember__c member = new Projectmember__c (Project__c = proj.id, Contact__c = cont.id);
        insert member;

        return member;
	}

	public static Hub_Building_Site__c createTestHub(String name, Projecten__c proj) {
		RecordType hRT = [select Id, Name from RecordType where Name = 'Hub'];

		Hub_Building_Site__c buldingSite;
		if (proj == null) {
			buldingSite = new Hub_Building_Site__c(RecordTypeId = hRT.id, Name = name);
		} else {
			buldingSite = new Hub_Building_Site__c(RecordTypeId = hRT.id, Name = name, Project__c = proj.id );
		}

        insert buldingSite;

        return buldingSite;
	}

	public static Hub_Building_Site__c createTestHubBuildingSite(String name, Projecten__c proj) {
		RecordType bsRT = [select Id, Name from RecordType where Name = 'Building Site'];

		Hub_Building_Site__c buldingSite;
		if (proj == null) {
			buldingSite = new Hub_Building_Site__c(RecordTypeId = bsRT.id, Name = name);
		} else {
			buldingSite = new Hub_Building_Site__c(RecordTypeId = bsRT.id, Name = name, Project__c = proj.id );
		}

        insert buldingSite;

        return buldingSite;
	}

	public static WWW__c createTestWww(Projecten__c project, Item__c item, Hub_Building_Site__c hub) {
		WWW__c www = new WWW__c();

		www.Project__c = project.Id;
		www.Item__c = item.Id;
		www.Hub_Building_Site__c = hub.Id;

		insert www;

		return www;
	}

	public static Location__c createTestGateLocation(String name) {
		RecordType gateRT = [select Id, Name from RecordType where Name = 'Gate'];

        Location__c gate = new Location__c(RecordTypeId = gateRT.id, Name = name );
        insert gate;

        return gate;
	}

	public static Location__c createTestHublocationParent(String name, Hub_Building_Site__c hub) {
		RecordType hublRT = [select Id, Name from RecordType where Name = 'Hublocation'];

		Location__c hubl = new Location__c(RecordTypeId = hublRT.id, Name = name, Hub_Building_Site__c = hub.id);
        insert hubl;

        return hubl;
	}

	public static List<Location__c> createTestHublocationChildren(Hub_Building_Site__c hub, Location__c parent) {
		List<String> sublocsNames = new List<String>{'A', 'B', 'C', 'D'};
		RecordType hublRT = [select Id, Name from RecordType where Name = 'Hublocation'];

		List<Location__c> toReturn = new List<Location__c>();
		for (String str : sublocsNames) {
			Location__c loc = new Location__c();
			loc.Name = parent.Name + str;
			loc.Parent_Location__c = parent.Id;
			loc.Hub_Building_Site__c = hub.Id;
			loc.RecordTypeId = hublRT.id;

			toReturn.add(loc);
		}

		insert toReturn;

		return toReturn;
	}

	public static List<Location__c> createTestMassGateLocationWithHub(String name, Integer count, Hub_Building_Site__c hub) {
		RecordType gateRT = [select Id, Name from RecordType where Name = 'Gate'];

        List<Location__c> locs = new List<Location__c>();
		for (Integer i=0; i< count; i++) {
			Location__c gate = new Location__c(RecordTypeId = gateRT.id, Name = name + String.valueOf(i), Hub_Building_Site__c = hub.id );
			locs.add(gate);
		}
		insert locs;

        return locs;
	}

	public static Location__c createTestSiteLocation(Hub_Building_Site__c buldingSite, String name) {
		RecordType siteRT = [select Id, Name from RecordType where Name = 'Site Location'];

        Location__c siteL = new Location__c(RecordTypeId = siteRT.id, Hub_Building_Site__c = buldingSite.id, Name = name);
        insert siteL;

        return siteL;
	}

	public static List<Location__c> createTestMassSiteLocationWithHub(String name, Integer count, Hub_Building_Site__c hub) {
		RecordType siteRT = [select Id, Name from RecordType where Name = 'Site Location'];

        List<Location__c> locs = new List<Location__c>();
		for (Integer i=0; i< count; i++) {
			Location__c gate = new Location__c(RecordTypeId = siteRT.id, Name = name + String.valueOf(i), Hub_Building_Site__c = hub.id );
			locs.add(gate);
		}
		insert locs;

        return locs;
	}

	public static Location__c createTestVerticalTransport(String name) {
		RecordType verRT = [select Id, Name from RecordType where Name = 'Vertical Transport'];

        Location__c verTr = new Location__c(RecordTypeId = verRT.id, Name = name);
        insert verTr;

        return verTr;
	}

	public static List<Location__c> createTestMassVerticalTransportWithHub(String name, Integer count, Hub_Building_Site__c hub) {
		RecordType verRT = [select Id, Name from RecordType where Name = 'Vertical Transport'];

        List<Location__c> locs = new List<Location__c>();
		for (Integer i=0; i< count; i++) {
			Location__c gate = new Location__c(RecordTypeId = verRT.id, Name = name + String.valueOf(i), Hub_Building_Site__c = hub.id );
			locs.add(gate);
		}
		insert locs;

        return locs;
	}
}