src/objects/Building_Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Date__c</fullName>
        <description>Delivery Date</description>
        <inlineHelpText>Delivery Date</inlineHelpText>
        <label>Delivery Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Help Text Hub/Building Site</inlineHelpText>
        <label>Hub/Building Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Hub_Building_Site__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Building Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bouwticket</label>
    <nameField>
        <displayFormat>BT-{00000}</displayFormat>
        <label>Naam van Building Ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bouwticket</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Hub_Building_Site__c.object
<CustomObject>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CalendarOnTicketExtension.cls
public with sharing class CalendarOnTicketExtension {
    public ComponentData componentData {get; set;}
    public CalendarOnTicketExtension(ApexPages.StandardController controller) {
        componentData = new ComponentData();
        Building_Ticket__c ticket = [select Id, Hub_Building_Site__c, Delivery_Date__c from Building_Ticket__c where id=:controller.getRecord().id ];
        componentData.hubSelected = ticket.Hub_Building_Site__c;

        String month = String.valueOf(ticket.Delivery_Date__c.month());
        String day = String.valueOf(ticket.Delivery_Date__c.day());
        if (month.length() == 1) {
        	month ='0'+month;
        }
        if (day.length() == 1) {
        	day ='0'+day;
        }
        componentData.dateSelected = String.valueOf(ticket.Delivery_Date__c.year()+'-'+month+'-'+day);
    }

}