src/objects/Building_Ticket__c.object
<CustomObject>
    <fields>
        <fullName>Arrival_Time__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Help Text Hub/Building Site</inlineHelpText>
        <label>Hub/Building Site</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Hub_Building_Site__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>Building Site</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipName>Building_Tickets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Assigned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Bouwticket</label>
    <nameField>
        <displayFormat>BT-{00000}</displayFormat>
        <label>Naam van Building Ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bouwticket</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Hub_Building_Site__c.object
<CustomObject>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ApprovingExtension.cls
public with sharing class ApprovingExtension {
	public ApprovingExtension() {
		
	}
	public Building_Ticket__c ticket {get;set;}
	public ApprovingExtension(ApexPages.StandardController controller) {
		ticket = [select Id, Status__c, Hub_Building_Site__c, Arrival_Time__c from Building_Ticket__c where id=: controller.getRecord().id];
		ticket.Status__c = 'Assigned';
		update ticket;
	}
	public pageReference runScript() {
		return new PageReference('/apex/Calendar?id='+ticket.Hub_Building_Site__c+'&dateFrom='+ticket.Arrival_Time__c);
	}
}