src/objects/Hub_Building_Site__c.object
<CustomObject>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <recordTypes>
        <fullName>Hub</fullName>
        <active>true</active>
        <label>Hub</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Locatie</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locaties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projecten__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Projectcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projecten</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projectmember__c.object
<CustomObject>
    <label>Projectmember</label>
    <nameField>
        <label>Projectmember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projectmembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WWW__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loods/HUB</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projectmember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Aanvrager</description>
        <inlineHelpText>Dit invulveld is bedoeld om de aanvrager te benoemen.</inlineHelpText>
        <label>Aanvrager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Projectmember__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Projectmember__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WWW</label>
    <nameField>
        <displayFormat>WWW-{0}</displayFormat>
        <label>WWW Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WWW</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectItemsAfroepenControllerTest.cls
@isTest
private class ProjectItemsAfroepenControllerTest {

	@testSetup static void setup() {
		TestDataGenerator.fillTriggerSwitcherValues();

		Account account = TestDataGenerator.createBouwticketAccount('testAccount');
        Contact contact = TestDataGenerator.createTestContact(account);

        Projecten__c project = TestDataGenerator.createTestProject(account, 'testestest');
        Projectmember__c member = TestDataGenerator.createTestProjectMember(project, contact);
        Hub_Building_Site__c buldingSite = TestDataGenerator.createTestHub('Test Hub', project);

        Item__c item = TestDataGenerator.createTestItem('TestItem', 1);
        Item__c item2 = TestDataGenerator.createTestItem('TestItem2', 1);
        Location__c hublocationParent = TestDataGenerator.createTestHublocationParent('20C3', buldingSite);
        List<Location__c> hublocationChilds = TestDataGenerator.createTestHublocationChildren(buldingSite, hublocationParent);

        WWW__c www = TestDataGenerator.createTestWww(project, item, buldingSite);
        WWW__c www2 = TestDataGenerator.createTestWww(project, item2, buldingSite);
        TestDataGenerator.createTestWwwDetailOntvangen(www, hublocationParent, 50);
        //TestDataGenerator.createTestWwwDetailOntvangen(www2, hublocationParent, 50);
	}

	@isTest static void test_AfroepenItemsCycle() {
		Test.startTest();
			PageReference pageRef = Page.ProjectItemsAfroepen;
			Test.setCurrentPage(pageRef);

			ProjectItemsAfroepenController contr = new ProjectItemsAfroepenController();

			List<Projecten__c> prjcts = contr.projectsFound;
			Boolean showItems = contr.showItems;
			Boolean showItemsForAfroepen = contr.showItemsForAfroepen;

			contr.getTimes();

			contr.searchline = 'test';
			contr.searchProjects();
			System.assertNotEquals(0, contr.projectsFound.size(), 'Should be more than 0 projects');

			contr.projectId = contr.projectsFound[0].Id;
			contr.selectItems();
			System.assertNotEquals(0, contr.listOfItems.size(), 'Should be more than 0 possible items ready for afroepen');

			contr.listOfItems[0].isSelected = true;
			contr.afroepenItems();
			System.assertNotEquals(0, contr.listForAfroepen.size(), 'Should be more than 0 possible items selected for afroepen');

			contr.listForAfroepen[0].isSelected = true;
			contr.listForAfroepen[0].itemsToInvoke = 10;
			contr.deliveryDate = Date.today().addDays(3);

			PageReference pr = contr.finishAfroepenItems();
			System.assertEquals('', contr.fieldsValidationError, 'No errors should be, all data set correctly');
		Test.stopTest();
	}

	@isTest static void test_AfroepenItemsSorting() {
		Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];
		WWW__c www2 = [Select Id, Name from WWW__c where Item__r.Name = 'TestItem2' limit 1];

		Test.startTest();
			TestDataGenerator.createTestWwwDetailOntvangen(www2, hublocationParent, 50);
			PageReference pageRef = Page.ProjectItemsAfroepen;
			Test.setCurrentPage(pageRef);

			ProjectItemsAfroepenController contr = new ProjectItemsAfroepenController();

			List<Projecten__c> prjcts = contr.projectsFound;
			Boolean showItems = contr.showItems;
			Boolean showItemsForAfroepen = contr.showItemsForAfroepen;

			contr.getTimes();

			contr.searchline = 'test';
			contr.searchProjects();
			System.assertNotEquals(0, contr.projectsFound.size(), 'Should be more than 0 projects');

			contr.projectId = contr.projectsFound[0].Id;
			contr.selectItems();
			System.assertNotEquals(0, contr.listOfItems.size(), 'Should be more than 0 possible items ready for afroepen');
		//Test.startTest();

			PageReference srt = contr.sortByFiledItem();

			contr.sortDirection = 'DESCENDING';
			contr.sortField = 'Name';
			srt = contr.sortByFiledItem();

			Set<String> fields = new Set<String>{'Staat', 'Maten', 'Diameter', 'Merk', 'Material', 'Kleur', 'Type_verpakking', 'wat_nog_op_te_roepen_is', 'Loods/HUB'};

			for (String str : fields) {
				contr.sortDirection = 'ASCENDING';
				contr.sortField = str;
				srt = contr.sortByFiledItem();
				contr.sortDirection = 'DESCENDING';
				srt = contr.sortByFiledItem();
			}
		Test.stopTest();
	}

	@isTest static void test_AfroepenItemsFiltering() {
		Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];
		WWW__c www2 = [Select Id, Name from WWW__c where Item__r.Name = 'TestItem2' limit 1];

		Test.startTest();
			TestDataGenerator.createTestWwwDetailOntvangen(www2, hublocationParent, 50);
			PageReference pageRef = Page.ProjectItemsAfroepen;
			Test.setCurrentPage(pageRef);

			ProjectItemsAfroepenController contr = new ProjectItemsAfroepenController();

			List<Projecten__c> prjcts = contr.projectsFound;
			Boolean showItems = contr.showItems;
			Boolean showItemsForAfroepen = contr.showItemsForAfroepen;

			contr.getTimes();

			contr.searchline = 'test';
			contr.searchProjects();
			System.assertNotEquals(0, contr.projectsFound.size(), 'Should be more than 0 projects');

			contr.projectId = contr.projectsFound[0].Id;
			contr.selectItems();
			System.assertNotEquals(0, contr.listOfItems.size(), 'Should be more than 0 possible items ready for afroepen');
		//Test.startTest();
			contr.getStaatPicklistValues();
			contr.getMaterialPicklistValues();
			contr.getKleurPicklistValues();
			contr.getKindOfPackagesPicklistValues();

			contr.addFiltersToItems();

			contr.seacrhByItemName = 'qwerty';
			contr.addFiltersToItems();
		Test.stopTest();
	}

	@isTest static void test_deliveryDateNotSet() {
		Test.startTest();
			PageReference pageRef = Page.ProjectItemsAfroepen;
			Test.setCurrentPage(pageRef);

			ProjectItemsAfroepenController contr = new ProjectItemsAfroepenController();

			contr.getTimes();

			contr.searchline = 'test';
			contr.searchProjects();
			System.assertNotEquals(0, contr.projectsFound.size(), 'Should be more than 0 projects');

			contr.projectId = contr.projectsFound[0].Id;
			contr.selectItems();
			System.assertNotEquals(0, contr.listOfItems.size(), 'Should be more than 0 possible items ready for afroepen');
		//Test.startTest();
			contr.listOfItems[0].isSelected = true;
			contr.afroepenItems();
			System.assertNotEquals(0, contr.listForAfroepen.size(), 'Should be more than 0 possible items selected for afroepen');

			contr.listForAfroepen[0].isSelected = true;
			contr.listForAfroepen[0].itemsToInvoke = 10;
			//contr.deliveryDate = Date.today().addDays(3);

			PageReference pr = contr.finishAfroepenItems();
			System.assertNotEquals('', contr.fieldsValidationError, 'Should be error that date not set');
		Test.stopTest();
	}

	@isTest static void test_numberOfItemsAfroepenBad() {
		Test.startTest();
			PageReference pageRef = Page.ProjectItemsAfroepen;
			Test.setCurrentPage(pageRef);

			ProjectItemsAfroepenController contr = new ProjectItemsAfroepenController();

			contr.getTimes();

			contr.searchline = 'test';
			contr.searchProjects();
			System.assertNotEquals(0, contr.projectsFound.size(), 'Should be more than 0 projects');

			contr.projectId = contr.projectsFound[0].Id;
			contr.selectItems();
			System.assertNotEquals(0, contr.listOfItems.size(), 'Should be more than 0 possible items ready for afroepen');

			contr.listOfItems[0].isSelected = true;
			contr.afroepenItems();
			System.assertNotEquals(0, contr.listForAfroepen.size(), 'Should be more than 0 possible items selected for afroepen');
		//Test.startTest();
			contr.listForAfroepen[0].isSelected = true;
			//contr.listForAfroepen[0].itemsToInvoke = 10;
			contr.deliveryDate = Date.today().addDays(3);

			PageReference pr = contr.finishAfroepenItems();
			System.assertNotEquals('', contr.fieldsValidationError, 'Should be error that number of items not set');

			contr.listForAfroepen[0].itemsToInvoke = 100;
			contr.deliveryDate = Date.today().addDays(3);

			pr = contr.finishAfroepenItems();
			System.assertNotEquals('', contr.fieldsValidationError, 'Error that number of items too big');
		Test.stopTest();
	}
}