src/objects/Hub_Building_Site__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Building Sites</relationshipLabel>
        <relationshipName>Hubs_Building_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <recordTypes>
        <fullName>Hub</fullName>
        <active>true</active>
        <label>Hub</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Toelichting__c</fullName>
        <label>Toelichting</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Locatie</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locaties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projectmember__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Projectmembers</relationshipLabel>
        <relationshipName>Projectmembers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Projectmember</label>
    <nameField>
        <label>Projectmember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projectmembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WWW__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loods/HUB</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Projectmember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Aanvrager</description>
        <inlineHelpText>Dit invulveld is bedoeld om de aanvrager te benoemen.</inlineHelpText>
        <label>Aanvrager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Projectmember__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Projectmember__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WWW</label>
    <nameField>
        <displayFormat>WWW-{0}</displayFormat>
        <label>WWW Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WWW</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WWW_Detail__c.object
<CustomObject>
    <description>Who What Where
Wie Wat Waar</description>
    <fields>
        <fullName>Afroepeenheid__c</fullName>
        <inlineHelpText>Hier aangeven op welke eenheid de klant de goederen weer gaat afroepen</inlineHelpText>
        <label>Afroepeenheid</label>
        <picklist>
            <picklistValues>
                <fullName>Balen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Big Bag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boxen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Container</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deellading vrachtwagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dozen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flessen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasbok Hout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasbok Staal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSA BAM Kar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haspels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kannen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kartons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kratten</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los gestort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pakken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pallets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stuks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tanks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vaten</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volledige vrachtwagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zakken</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Arrival_Truck_On_Hub__c</fullName>
        <label>Arrival Truck On Hub</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Arrival_Truck_On_Project__c</fullName>
        <label>Datum en tijd klaargezet</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Compleet_klaargezet__c</fullName>
        <label>Compleet klaargezet</label>
        <picklist>
            <picklistValues>
                <fullName>Ja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Damage_Package__c</fullName>
        <label>Damage Package</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Einddatum_opslag__c</fullName>
        <label>Einddatum opslag</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Grootte_verpakking__c</fullName>
        <label>Grootste verpakking</label>
        <picklist>
            <picklistValues>
                <fullName>Balen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Big Bag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boxen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Container</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deellading vrachtwagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dozen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flessen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasbok Hout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasbok Staal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSA BAM Kar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haspels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kannen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kartons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kratten</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los gestort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pakken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pallets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stuks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tanks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vaten</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volledige vrachtwagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zakken</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Itemlocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_Of_Items__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Aantal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opslagduur__c</fullName>
        <label>Opslagduur</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projectcode</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>WWW-Detail</relationshipLabel>
        <relationshipName>Itemlocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projectmember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projectmember</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Projectmember__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Projectmember__c</referenceTo>
        <relationshipName>Itemlocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reden_niet_compleet_uigevoerd__c</fullName>
        <label>Reden niet compleet uitgevoerd</label>
        <picklist>
            <picklistValues>
                <fullName>(deels) niet aanwezig</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stuk</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Toelichting__c</fullName>
        <label>Toelichting</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>WWW__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WWW</label>
        <referenceTo>WWW__c</referenceTo>
        <relationshipLabel>WWW-Detail (WWW)</relationshipLabel>
        <relationshipName>WWW_Detail1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WWW-Detail</label>
    <nameField>
        <displayFormat>WWW-D-{0}</displayFormat>
        <label>WWW Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WWW-Detail</pluralLabel>
    <recordTypes>
        <fullName>Delivered_2_Hub</fullName>
        <active>true</active>
        <label>Ontvangen</label>
    </recordTypes>
    <recordTypes>
        <fullName>Invoked</fullName>
        <active>true</active>
        <label>Afroepen</label>
    </recordTypes>
    <recordTypes>
        <fullName>Reserved</fullName>
        <active>true</active>
        <label>Verwachten</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WWWDetailExtensionTest.cls
@isTest
private class WWWDetailExtensionTest {

	@testSetup static void setup() {
		TestDataGenerator.fillTriggerSwitcherValues();

		Account account = TestDataGenerator.createBouwticketAccount('testAccount');
        Contact contact = TestDataGenerator.createTestContact(account);

        Projecten__c project = TestDataGenerator.createTestProject(account, 'testestest');
        Projectmember__c member = TestDataGenerator.createTestProjectMember(project, contact);
        Hub_Building_Site__c buldingSite = TestDataGenerator.createTestHub('Test Hub', project);

        Item__c item = TestDataGenerator.createTestItem('TestItem', 1);
        Location__c hublocationParent = TestDataGenerator.createTestHublocationParent('20C3', buldingSite);
        List<Location__c> hublocationChilds = TestDataGenerator.createTestHublocationChildren(buldingSite, hublocationParent);
        System.debug('hublocationChilds -->> ' + hublocationChilds);

        WWW__c www = TestDataGenerator.createTestWww(project, item, buldingSite);
	}

	@isTest static void test_createOntvangen() {
		WWW__c www = [Select Id, Name from WWW__c limit 1];
        Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];

        Test.startTest();
        	ApexPages.StandardController sc = new ApexPages.StandardController(www);
        	WWWDetailExtension ctrl = new WWWDetailExtension(sc);

        	/** CREATE TEST ONTVANGEN **/
	        	PageReference tpageRef = ctrl.redirectDelToHub();
	        	Test.setCurrentPage(tpageRef);
	        	ctrl = new WWWDetailExtension(sc);
	        	System.assertEquals(true, ctrl.delToHub);

	        	ctrl.getTimes();

	        	ctrl.detail.Location__c = hublocationParent.Id;
	        	ctrl.detail.Number_Of_Items__c = 10;
	        	ctrl.detail.Damage_Package__c = 'No';

				System.currentPageReference().getParameters().put('Arrival_Truck_On_Hub__c','25.04.2017');
	        	System.currentPageReference().getParameters().put('Einddatum_opslag__c','29.04.2017');

	        	ctrl.getSubs();
	        	System.assertNotEquals(0, ctrl.sublocations1.size());

	        	for(SubLocation subLoc : ctrl.sublocations1) {
	        		subLoc.isChecked = true;
	        	}

	        	ctrl.saveDetail();
	        	WWW_Detail__c toCheck = [Select Id, RecordType.Name, Number_Of_Items__c from WWW_Detail__c where RecordType.DeveloperName = 'Delivered_2_Hub' limit 1];
	        	System.assertEquals(toCheck.Id, ctrl.detail.Id);
        	/** END CREATE TEST ONTVANGEN **/

        Test.stopTest();

        toCheck.Number_Of_Items__c = 100;
        update toCheck;

        delete toCheck;
	}

	@isTest static void test_createOntvangenNegative() {
		WWW__c www = [Select Id, Name from WWW__c limit 1];
        Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];

        Test.startTest();
        	ApexPages.StandardController sc = new ApexPages.StandardController(www);
        	WWWDetailExtension ctrl = new WWWDetailExtension(sc);

        	/** CREATE TEST ONTVANGEN **/
	        	PageReference tpageRef = ctrl.redirectDelToHub();
	        	Test.setCurrentPage(tpageRef);
	        	ctrl = new WWWDetailExtension(sc);
	        	System.assertEquals(true, ctrl.delToHub);

	        	ctrl.getTimes();

	        	ctrl.detail.Location__c = hublocationParent.Id;
	        	ctrl.detail.Damage_Package__c = 'No';

				System.currentPageReference().getParameters().put('Arrival_Truck_On_Hub__c','25.04.2017');
	        	System.currentPageReference().getParameters().put('Einddatum_opslag__c','29.04.2017');

	        	ctrl.getSubs();
	        	System.assertNotEquals(0, ctrl.sublocations1.size());

	        	for(SubLocation subLoc : ctrl.sublocations1) {
	        		subLoc.isChecked = true;
	        	}

	        	ctrl.saveDetail();
	        	System.assertNotEquals(0, ctrl.fieldsValidationError.length());
        	/** END CREATE TEST ONTVANGEN **/

        Test.stopTest();
	}

	@isTest static void test_createAfleveren() {
		WWW__c www = [Select Id, Name from WWW__c limit 1];
        Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];

    	/** CREATE TEST ONTVANGEN **/
    	TestDataGenerator.createTestWwwDetailOntvangen(www, hublocationParent, 10);
    	/** END CREATE TEST ONTVANGEN **/

        Test.startTest();
        	ApexPages.StandardController sc = new ApexPages.StandardController(www);
    		WWWDetailExtension ctrl = new WWWDetailExtension(sc);
        	/** CREATE TEST AFLEVEREN **/
	        	PageReference tpageRef = ctrl.redirectDelToProj();
	        	Test.setCurrentPage(tpageRef);
	        	ctrl = new WWWDetailExtension(sc);
	        	System.assertEquals(true, ctrl.delToProj);

	        	ctrl.detail.Number_Of_Items__c = 5;
	        	ctrl.detail.Compleet_klaargezet__c = 'Ja';

	        	List<SelectOption> locsForAfleveren = ctrl.getLocationsForDelToPr();
	        	System.assert(!locsForAfleveren.isEmpty());

	        	ctrl.detail.Location__c = locsForAfleveren.get(1).getValue();

	        	ctrl.getOccupiedSubs();
	        	for (AfleverenSublocs subLoc : ctrl.occupiedSublocs) {
	        		subLoc.isChecked = true;
	        	}

	        	System.currentPageReference().getParameters().put('Arrival_Truck_On_Project__c', '27.04.2017');

	        	ctrl.saveDetail();

	        	/*----------------------------------------------------------------*/

	        	tpageRef = ctrl.redirectDelToProj();
	        	Test.setCurrentPage(tpageRef);
	        	ctrl = new WWWDetailExtension(sc);
	        	System.assertEquals(true, ctrl.delToProj);

	        	ctrl.detail.Number_Of_Items__c = 5;
	        	ctrl.detail.Compleet_klaargezet__c = 'Nee';
	        	ctrl.detail.Reden_niet_compleet_uigevoerd__c = 'Stuk';
	        	ctrl.detail.Toelichting__c = 'Test decription';

	        	locsForAfleveren = ctrl.getLocationsForDelToPr();
	        	System.assert(!locsForAfleveren.isEmpty());

	        	ctrl.detail.Location__c = locsForAfleveren.get(1).getValue();

	        	ctrl.getOccupiedSubs();
	        	for (AfleverenSublocs subLoc : ctrl.occupiedSublocs) {
	        		subLoc.isChecked = true;
	        	}

	        	System.currentPageReference().getParameters().put('Arrival_Truck_On_Project__c', '29.04.2017');

	        	ctrl.saveDetail();
        	/** CREATE TEST AFLEVEREN **/

        Test.stopTest();
	}

	@isTest static void test_createVerwachten() {
		WWW__c www = [Select Id, Name from WWW__c limit 1];
        Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];

    	/** CREATE TEST ONTVANGEN **/
    	TestDataGenerator.createTestWwwDetailOntvangen(www, hublocationParent, 10);
    	/** END CREATE TEST ONTVANGEN **/

        Test.startTest();
        	ApexPages.StandardController sc = new ApexPages.StandardController(www);
    		WWWDetailExtension ctrl = new WWWDetailExtension(sc);

    		/** CREATE TEST VERWACHTEN  **/
    			PageReference tpageRef = ctrl.redirectReserved();
    			Test.setCurrentPage(tpageRef);
	        	ctrl = new WWWDetailExtension(sc);
	        	System.assertEquals(true, ctrl.reserved);

	        	//List<SelectOption> projectsList = ctrl.getProjects();
	        	//ctrl.detail.Project__c = projectsList.get(0).getValue();

	        	ctrl.detail.Grootte_verpakking__c = 'Balen';
	        	ctrl.detail.Number_Of_Items__c = 5;
	        	ctrl.detail.Afroepeenheid__c = 'Balen';

	        	System.currentPageReference().getParameters().put('Date_Of_Delivery', '29.04.2017');
	        	System.currentPageReference().getParameters().put('Opslagduur__c', '29.04.2017');

	        	ctrl.saveDetail();
    		/** END CREATE TEST VERWACHTEN  **/
        Test.stopTest();
    }

    @isTest static void test_createAfroepen() {
		WWW__c www = [Select Id, Name from WWW__c limit 1];
        Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];

    	/** CREATE TEST ONTVANGEN **/
    	TestDataGenerator.createTestWwwDetailOntvangen(www, hublocationParent, 10);
    	/** END CREATE TEST ONTVANGEN **/

        Test.startTest();
        	ApexPages.StandardController sc = new ApexPages.StandardController(www);
    		WWWDetailExtension ctrl = new WWWDetailExtension(sc);

    		/** CREATE TEST AFROEPEN  **/
    			PageReference tpageRef = Page.New_Invoked;
    			ApexPages.currentPage().getParameters().put('id', www.Id);

    			Test.setCurrentPage(tpageRef);
	        	System.assertEquals(true, ctrl.invoked);

	        	ctrl.detail.Number_Of_Items__c = 5;
	        	System.currentPageReference().getParameters().put('Preferred_Delivery_Time__c', '29.04.2017');

	        	ctrl.saveDetail();
    		/** END CREATE TEST AFROEPEN  **/
        Test.stopTest();
    }

    @istest static void test_failCreateRecvords() {
    	Item__c item = TestDataGenerator.createTestItem('TestItem2', 1);
    	Hub_Building_Site__c buldingSite = [Select Id from Hub_Building_Site__c where Name = 'Test Hub' limit 1];
    	Projecten__c project = [Select Id from Projecten__c where Name = 'testestest' limit 1];
        WWW__c www = TestDataGenerator.createTestWww(project, item, buldingSite);

        Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];

        Test.startTest();
        	ApexPages.StandardController sc = new ApexPages.StandardController(www);
        	WWWDetailExtension ctrl = new WWWDetailExtension(sc);

        	/** CREATE TEST ONTVANGEN **/
	        	PageReference tpageRef = ctrl.redirectDelToHub();
	        	Test.setCurrentPage(tpageRef);
	        	ctrl = new WWWDetailExtension(sc);
	        	System.assertEquals(true, ctrl.delToHub);

	        	ctrl.getTimes();

	        	ctrl.detail.Location__c = hublocationParent.Id;
	        	ctrl.detail.Number_Of_Items__c = 10;
	        	ctrl.detail.Damage_Package__c = 'No';

				System.currentPageReference().getParameters().put('Arrival_Truck_On_Hub__c','25.04.2017');
	        	System.currentPageReference().getParameters().put('Einddatum_opslag__c','29.04.2017');

	        	ctrl.getSubs();
	        	System.assertNotEquals(0, ctrl.sublocations1.size());

	        	for(SubLocation subLoc : ctrl.sublocations1) {
	        		subLoc.isChecked = true;
	        	}

	        	delete www;

	        	ctrl.saveDetail();
        	/** END CREATE TEST ONTVANGEN **/

        Test.stopTest();
    }
}