src/objects/Hub_Building_Site__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Building Sites</relationshipLabel>
        <relationshipName>Hubs_Building_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Diameter__c</fullName>
        <inlineHelpText>Diameter in mm</inlineHelpText>
        <label>Diameter</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Kind_Of_Packages__c</fullName>
        <inlineHelpText>Let op: de geselecteerde verpakking moet de eenheid zijn waarop het item afgeroepen gaat worden. Dus per stuk leveren is verpakking stuks of als de klant het per doos wil is de verpakking doos</inlineHelpText>
        <label>Kind Of Packages</label>
        <picklist>
            <picklistValues>
                <fullName>Balen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Big Bag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bok</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boxen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Container</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deellading vrachtwagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dozen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flessen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasbok Hout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasbok Staal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSA BAM Kar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haspels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kannen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kartons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kooikar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kratten</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los gestort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pakken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pallets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stuks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tanks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vaten</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volledige vrachtwagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zakken</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Kleur__c</fullName>
        <label>Kleur</label>
        <picklist>
            <picklistValues>
                <fullName>Aluminium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antraciet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beige</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beuken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bordeaux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bruin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donkerblauw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eiken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grijs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kersen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lichtblauw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oranje</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rose</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zwart</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Materiaal__c</fullName>
        <label>Materiaal</label>
        <picklist>
            <picklistValues>
                <fullName>Aluminium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kunststof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metaal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Papier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plastic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plexiglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rubber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Steen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trespa</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Merk__c</fullName>
        <label>Merk</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sizes__c</fullName>
        <formula>&apos;L: &apos; +TEXT(Length__c)+ &apos; x W: &apos;+ TEXT(Width__c) + &apos; x H: &apos; + TEXT(Height__c)</formula>
        <label>Sizes</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staat__c</fullName>
        <label>Staat</label>
        <picklist>
            <picklistValues>
                <fullName>Beschadigd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gebruikt &gt; Inzetbaar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gebruikt &gt; Inzetbaar &gt; Gedemonteerd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gebruikt &gt; Niet inzetbaar &gt; Repareren</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gebruikt &gt; Niet inzetbaar &gt; Schoonmaken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gereviseerd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nader te bepalen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nieuw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onbekend</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Projecten__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Projectcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projecten</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/WWW__c.object
<CustomObject>
    <fields>
        <fullName>Curr_Items_To_Invoke__c</fullName>
        <formula>Total_Items_Delivered_Hub__c - Total_Items_Invoked__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Huidige items die we kunnen oproepen (items geleverd op Hub - opgeroepen items)</inlineHelpText>
        <label>Curr Items To Invoke</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loods/HUB</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>WWW</label>
    <nameField>
        <displayFormat>WWW-{0}</displayFormat>
        <label>WWW Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WWW</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WWW_Detail__c.object
<CustomObject>
    <description>Who What Where
Wie Wat Waar</description>
    <fields>
        <fullName>Extra_Remarks__c</fullName>
        <label>Opmerkingen</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Kind_Of_Packages__c</fullName>
        <formula>TEXT(WWW__r.Item__r.Kind_Of_Packages__c)</formula>
        <label>Kind Of Packages</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_Of_Items__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Aantal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Preferred_Delivery_Time__c</fullName>
        <label>Preferred Delivery Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projectcode</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>WWW-Detail</relationshipLabel>
        <relationshipName>Itemlocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sizes__c</fullName>
        <formula>&apos;L: &apos; +TEXT(Length__c)+ &apos; x W: &apos;+ TEXT(Width__c) + &apos; x H: &apos; + TEXT(Height__c)</formula>
        <inlineHelpText>Kubieke meters LxWxH</inlineHelpText>
        <label>Sizes</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>WWW__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WWW</label>
        <referenceTo>WWW__c</referenceTo>
        <relationshipLabel>WWW-Detail (WWW)</relationshipLabel>
        <relationshipName>WWW_Detail1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WWW-Detail</label>
    <nameField>
        <displayFormat>WWW-D-{0}</displayFormat>
        <label>WWW Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WWW-Detail</pluralLabel>
    <recordTypes>
        <fullName>Invoked</fullName>
        <active>true</active>
        <label>Afroepen</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProjectItemsAfroepenController.cls
public with sharing class ProjectItemsAfroepenController {
	public List<Projecten__c> projectsFound {
		get {
			if (projectsFound == null) {
				projectsFound = new List<Projecten__c>();
			}
			return projectsFound;
		} set;
	}

	public Boolean showItems {
		get {
			if (showItems == null) {
				showItems = false;
			}
			return showItems;
		} set;
	}

	public Boolean showItemsForAfroepen {
		get {
			if (showItemsForAfroepen == null) {
				showItemsForAfroepen = false;
			}
			return showItemsForAfroepen;
		} set;
	}

	public Date deliveryDate {
		get {
			if (deliveryDate == null) {
				//deliveryDate = Date.today();
			}
			return deliveryDate;
		} set;
	}

	public String selectedTime {
        get {
            if(selectedTime == null)
            {
                selectedTime = '8:00';
            }
            return selectedTime;
        } set;
    }

	public List<ItemsList> listOfItems {get; set;}
	public List<ItemsList> listForAfroepen {get; set;}

	public String searchline {get; set;}
	public String projectId {get; set;}
	public String extraRemark {get; set;}
	public String sortDirection {get;set;}
    public String sortField {get;set;}

    /* Filters */
    public String seacrhByItemName {get; set;}
    public String selectedStaat {get; set;}
    public String seacrhByItemSize {get; set;}
    public String seacrhByItemDiameter {get; set;}
    public String seacrhByItemMerk {get; set;}
    public String selectedMaterial {get; set;}
    public String selectedKleur {get; set;}
    public String selectedKindOfPackages {get; set;}
    public String seacrhByHub {get; set;}

	public Boolean showSuccessPopup {get; set;}

	public Map<Id, Projecten__c> projectsById {get; set;}

	@TestVisible String fieldsValidationError = '';

	public ProjectItemsAfroepenController() {
		showSuccessPopup = false;
	}

	public void searchProjects() {
		projectsFound = new List<Projecten__c>();

		String searchString = '%' + searchline + '%';
		projectsById = new Map<Id, Projecten__c>([Select Id, Name from Projecten__c WHERE Name LIKE :searchString LIMIT 5]);

		projectsFound.addAll(projectsById.values());
	}

	public void selectItems() {
		showItems = true;
		showItemsForAfroepen = false;
		showSuccessPopup = false;

		fieldsValidationError = '';

		listForAfroepen = new List<ItemsList>();
		listOfItems = new List<ItemsList>();

		List<WWW__c> wwws = [SELECT Id, Name, Project__c, Hub_Building_Site__c, Hub_Building_Site__r.Name, Curr_Items_To_Invoke__c, Item__c, Item__r.Name, Item__r.Staat__c, Item__r.Sizes__c,
										Item__r.Diameter__c, Item__r.Merk__c, Item__r.Materiaal__c, Item__r.Kleur__c, Item__r.Kind_Of_Packages__c
								FROM WWW__c
								WHERE Project__c = :projectId];

		if (wwws != null && !wwws.isEmpty()) {
			for (WWW__c www : wwws) {
				if (www.Curr_Items_To_Invoke__c > 0) {
					listOfItems.add(new ItemsList(www, true));
				}
			}
		}

		System.debug(listOfItems);
	}

	public void afroepenItems() {
		showItemsForAfroepen = true;
		listForAfroepen = new List<ItemsList>();
		fieldsValidationError = '';

		for (ItemsList il : listOfItems) {
			if (il.isSelected == true) {
				listForAfroepen.add(il);
			}
		}
	}

	public PageReference finishAfroepenItems() {
		System.debug('deliveryDate -->> ' + deliveryDate);

		fieldsValidationError = validateDateField();
		for (ItemsList il : listForAfroepen) {
			if (il.itemsToInvoke > il.wwwRecord.Curr_Items_To_Invoke__c) {
				fieldsValidationError += 'Max aantal items for ' + il.wwwRecord.Item__r.Name + ' item is ' + il.wwwRecord.Curr_Items_To_Invoke__c + ' <br/>';
			} else if (il.itemsToInvoke == null || il.itemsToInvoke == 0 || il.itemsToInvoke < 0) {
				fieldsValidationError += 'Aantal items for ' + il.wwwRecord.Item__r.Name + ' item should be > 0 <br/>';
			}
		}

		if (fieldsValidationError != '' && fieldsValidationError.length() > 0) {
            System.debug('ERROR -->> ' + fieldsValidationError);
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR, fieldsValidationError, '');
            ApexPages.addMessage(myMsg);
            return null;
        } else {
        	List<WWW_Detail__c> toInsert = new List<WWW_Detail__c>();

        	RecordType recType = [Select Id, Name from RecordType where sObjectType = 'WWW_Detail__c' and DeveloperName = 'Invoked' limit 1];

        	Datetime dateOfDelivery = makeDatetime(deliveryDate, selectedTime);
        	System.debug('dateOfDelivery -->> ' + dateOfDelivery);

        	String itemsAfroepen = '';
            String itemsAfroepenLinks = '';

            String fullURL = URL.getSalesforceBaseUrl().toExternalForm() + '/';

        	for (ItemsList il : listForAfroepen) {
        		WWW_Detail__c det = new WWW_Detail__c();
        		det.WWW__c = il.wwwRecord.Id;
        		det.RecordTypeId = recType.Id;
        		det.Number_Of_Items__c = il.itemsToInvoke;
        		det.Extra_Remarks__c = extraRemark;
        		det.Preferred_Delivery_Time__c = dateOfDelivery;

                insert det;

        		itemsAfroepen += il.wwwRecord.Item__r.Name + ' ( ' +  il.itemsToInvoke + ' ) \n';
                itemsAfroepenLinks += '<a href="' + fullURL + det.Id + '" >' + il.wwwRecord.Item__r.Name + ' ( ' +  il.itemsToInvoke + ' ) </a> <br />';
                System.debug('itemsAfroepenLinks -->> ' + itemsAfroepenLinks);
        		//System.debug('OBDEB DETAIL FOR ' + il.wwwRecord.Item__r.Name2 + ' -->> ' + det);
        		//toInsert.add(det);
        	}

        	//insert toInsert;

        	AfroepenAgenda__c afroepenAgenda = new AfroepenAgenda__c();
        	afroepenAgenda.Extra_Remarks__c = extraRemark;
        	afroepenAgenda.Preferred_Delivery_Time__c = dateOfDelivery;
        	//afroepenAgenda.End_Delivery_Time__c = makeDatetime(deliveryDate, '23:59');
        	afroepenAgenda.ItemsAfroepen__c = itemsAfroepen;
            afroepenAgenda.ItemsList__c = itemsAfroepenLinks;
        	afroepenAgenda.Project__c = projectId;

        	insert afroepenAgenda;

        	selectItems();
        	showItemsForAfroepen = false;

        	showSuccessPopup = true;
        }

		return null;
	}

	private String validateDateField() {
		String toReturn = '';

		if (deliveryDate == null) {
			//toReturn = 'Voorkeur afleverdatum is required field <br/>';
			toReturn = System.Label.Preferred_Delivery_Time + ' ' + System.Label.is_required_field + ' <br/>';
		}

		return toReturn;
	}

	private Datetime makeDatetime (Date dateVal, String timeStr) {
		Datetime toReturn = null;

		if (dateVal != null && timeStr != null) {
			Integer hours  = Integer.valueOf(timeStr.substring(0, timeStr.indexOf(':')));
	        Integer min = Integer.valueOf(timeStr.substring(timeStr.indexOf(':') + 1, timeStr.length()));

	        String dateStr = String.valueOf(dateVal);

			toReturn = Datetime.newInstance(Integer.valueOf(dateStr.substring(0,4)),
	                                    Integer.valueOf(dateStr.substring(5,7)), Integer.valueOf(dateStr.substring(8,10)), hours, min, 0);
		}

		return toReturn;
	}

	public List<SelectOption> getTimes() {
        List<SelectOption> options = WWWDetailHelper.fillTimesSelectList();

        return options;
    }

    public PageReference sortByFiledItem() {
        if (sortDirection == null || sortDirection == '') {
            sortDirection  = 'ASCENDING';
            sortField = 'Name';
        }

        ItemsList.SortDirection = sortDirection;
        ItemsList.SortField = sortField;
        this.listOfItems.sort();

        return null;
    }

    public void addFiltersToItems() {
    	if (seacrhByItemName == null) {
            seacrhByItemName = '';
        }

        if (selectedStaat == null) {
            selectedStaat = '';
        }

        if (seacrhByItemSize == null) {
            seacrhByItemSize = '';
        }

        if (seacrhByItemDiameter == null) {
            seacrhByItemDiameter = '';
        }

        if (seacrhByItemMerk == null) {
            seacrhByItemMerk = '';
        }

        if (selectedMaterial == null) {
        	selectedMaterial = '';
        }

        if (selectedKleur == null) {
        	selectedKleur = '';
        }

		if (selectedKindOfPackages == null) {
        	selectedKindOfPackages = '';
        }

		if (seacrhByHub == null) {
        	seacrhByHub = '';
        }
        for (ItemsList il : listOfItems) {
        	String diameterString = il.wwwRecord.Item__r.Diameter__c == null ? '' : String.valueOf(il.wwwRecord.Item__r.Diameter__c);
        	String merkString = il.wwwRecord.Item__r.Merk__c == null ? '' : String.valueOf(il.wwwRecord.Item__r.Merk__c);
        	String hubString = il.wwwRecord.Hub_Building_Site__r.Name == null ? '' : String.valueOf(il.wwwRecord.Hub_Building_Site__r.Name);

        	if (il.wwwRecord.Item__r.Name.containsIgnoreCase(seacrhByItemName)
        			&& (il.wwwRecord.Item__r.Staat__c != null && (il.wwwRecord.Item__r.Staat__c).contains(selectedStaat) || selectedStaat == 'Alle' || selectedStaat == '')
        			&& (il.wwwRecord.Item__r.Sizes__c.containsIgnoreCase(seacrhByItemSize))
        			&& (diameterString.containsIgnoreCase(seacrhByItemDiameter))
        			&& (merkString.containsIgnoreCase(seacrhByItemMerk))
        			&& (il.wwwRecord.Item__r.Materiaal__c != null && (il.wwwRecord.Item__r.Materiaal__c).contains(selectedMaterial) || selectedMaterial == 'Alle' || selectedMaterial == '')
        			&& (il.wwwRecord.Item__r.Kleur__c != null && (il.wwwRecord.Item__r.Kleur__c).contains(selectedKleur) || selectedKleur == 'Alle' || selectedKleur == '')
        			&& (il.wwwRecord.Item__r.Kind_Of_Packages__c != null && (il.wwwRecord.Item__r.Kind_Of_Packages__c).contains(selectedKindOfPackages) || selectedKindOfPackages == 'Alle' || selectedKindOfPackages == '')
        			&& (hubString.containsIgnoreCase(seacrhByHub))
        		) {
                il.show = true;
            } else {
                il.show = false;
            }

            if (seacrhByItemName == ''
            		&& (selectedStaat == 'Alle' || selectedStaat == '')
            		&& (seacrhByItemSize == '')
            		&& (seacrhByItemDiameter == '')
            		&& (seacrhByItemMerk == '')
            		&& (selectedMaterial == 'Alle' || selectedMaterial == '')
            		&& (selectedKleur == 'Alle' || selectedKleur == '')
            		&& (selectedKindOfPackages == 'Alle' || selectedKindOfPackages == '')
            		&& (seacrhByHub == '')
            	) {
                il.show = true;
            }
		}
    }

    public List<SelectOption> getStaatPicklistValues() {
    	List<SelectOption> options = new List<SelectOption>();

    	options.add(new SelectOption('Alle', 'Alle'));

    	Schema.DescribeFieldResult fieldResult = Item__c.Staat__c.getDescribe();
    	List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

    	for (Schema.PicklistEntry f : ple) {
    		options.add(new SelectOption(f.getLabel(), f.getValue()));
    	}

    	return options;
    }

    public List<SelectOption> getMaterialPicklistValues() {
    	List<SelectOption> options = new List<SelectOption>();

    	options.add(new SelectOption('Alle', 'Alle'));

    	Schema.DescribeFieldResult fieldResult = Item__c.Materiaal__c.getDescribe();
    	List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

    	for (Schema.PicklistEntry f : ple) {
    		options.add(new SelectOption(f.getLabel(), f.getValue()));
    	}

    	return options;
    }

    public List<SelectOption> getKleurPicklistValues() {
    	List<SelectOption> options = new List<SelectOption>();

    	options.add(new SelectOption('Alle', 'Alle'));

    	Schema.DescribeFieldResult fieldResult = Item__c.Kleur__c.getDescribe();
    	List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

    	for (Schema.PicklistEntry f : ple) {
    		options.add(new SelectOption(f.getLabel(), f.getValue()));
    	}

    	return options;
    }

    public List<SelectOption> getKindOfPackagesPicklistValues() {
    	List<SelectOption> options = new List<SelectOption>();

    	options.add(new SelectOption('Alle', 'Alle'));

    	Schema.DescribeFieldResult fieldResult = Item__c.Kind_Of_Packages__c.getDescribe();
    	List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

    	for (Schema.PicklistEntry f : ple) {
    		options.add(new SelectOption(f.getLabel(), f.getValue()));
    	}

    	return options;
    }
}