src/objects/Hub_Building_Site__c.object
<CustomObject>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <recordTypes>
        <fullName>Hub</fullName>
        <active>true</active>
        <label>Hub</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Locatie</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locaties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LocationPrintControllerTest.cls
@isTest
private class LocationPrintControllerTest {

	@isTest static void test_method_one() {
		TestDataGenerator.fillTriggerSwitcherValues();

		Hub_Building_Site__c hub = TestDataGenerator.createTestHubBuildingSite('Test Building Site', null);
		Hub_Building_Site__c hub1 = TestDataGenerator.createTestHubBuildingSite('Test Building Site2', null);

		List<Location__c> locs = TestDataGenerator.createTestMassGateLocationWithHub('TestGate', 600, hub);

		locs = TestDataGenerator.createTestMassSiteLocationWithHub('Test Site Location', 600, hub);

		locs = TestDataGenerator.createTestMassVerticalTransportWithHub('Test Vertical Transport', 600, hub1);


		LocationsPrintController ctrl = new LocationsPrintController();
		LocationsPrintController.getHubs();
		LocationsPrintController.loadData();
		ctrl.init();

		System.assertEquals(999, LocationsPrintController.locations.size());

		LocationsPrintController.hubSelected = hub.id;
		LocationsPrintController.loadData();

		System.assertEquals(999, LocationsPrintController.locations.size());
	}
}