src/objects/Hub_Building_Site__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Projecten__c</referenceTo>
        <relationshipLabel>Building Sites</relationshipLabel>
        <relationshipName>Hubs_Building_Sites</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projecten__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account (klant)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Projectcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projecten</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>AccountId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/HubUtil.cls
public without sharing class HubUtil {
	public static void entry(TriggerParams triggerParams) {
        List<Hub_building_site__c> triggerNew = (List<Hub_building_site__c>)triggerParams.triggerNew;
        List<Hub_building_site__c> triggerOld = (List<Hub_building_site__c>)triggerParams.triggerOld;
        Map<Id, Hub_building_site__c> oldMap = (Map<Id, Hub_building_site__c>)triggerParams.oldMap;
        Map<Id, Hub_building_site__c> newMap = (Map<Id, Hub_building_site__c>)triggerParams.newMap;
        if (triggerParams.isAfter){
          if (triggerParams.isUpdate || triggerParams.isInsert) {
           shareToForceUsers(newMap);
          }
        }
    }
    public static void shareToForceUsers (Map <Id, Hub_building_site__c> locById){
        List <Hub_building_site__c> tickets = [select Id, Project__r.Account__c , OwnerId 
                                            from Hub_building_site__c where id in: locById.keySet() ];
        Set <Id> accIds = new Set <Id>();
        for (Hub_building_site__c t: tickets) {
            if (t.Project__r.Account__c != null) {
                accIds.add(t.Project__r.Account__c);
            }
        }
        System.debug('accs '+ accIds);
        List <User> users = [select Id, isActive from User where AccountId__c in :accIds and isActive = true];
        Map <Id, User> userById = new Map <Id, User>(users);
        System.debug('users' + users.size() + ' '  + users);
        List <Hub_building_site__Share> sharingTicket = [SELECT  ParentId, Id, UserOrGroupId 
                                                FROM Hub_building_site__Share where ParentId in: locById.keySet()  ];
        System.debug(sharingTicket.size() + ' ' + sharingTicket);
        Map <Id, Map<Id, Hub_building_site__Share>> shareByUserByTicket = new Map <Id, Map<Id, Hub_building_site__Share>>();
        for (Hub_building_site__Share sh: sharingTicket) {
            if (shareByUserByTicket.containsKey(sh.ParentId)) {
                shareByUserByTicket.get(sh.ParentId).put(sh.UserOrGroupId, sh);
            } else {
                Map <Id, Hub_building_site__Share> shByUser = new Map <Id, Hub_building_site__Share>();
                shareByUserByTicket.put(sh.ParentId, shByUser);
            }
        }
        System.debug('shareByUserByTicket' + shareByUserByTicket.size() + ' '  + shareByUserByTicket);
        List <Hub_building_site__Share> newSharings = new List <Hub_building_site__Share>();
        for (Hub_building_site__c t: tickets) {
            for (User u: users) {
                System.debug('shareByUserByTicket.get(t.id)' + shareByUserByTicket.get(t.id) + ' ' + u.id);
                if (!shareByUserByTicket.get(t.id).containsKey(u.Id) && t.OwnerId != u.id && u.isActive ) {
                    newSharings.add(new Hub_building_site__Share(ParentId = t.id, UserOrGroupId = u.Id, AccessLevel = 'Edit'));
                }
            }
        }
        System.debug('add sharings ' + newSharings.size() + ' ' + newSharings);
        insert newSharings;
    }
}