src/objects/Hub_Building_Site__c.object
<CustomObject>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <recordTypes>
        <fullName>Hub</fullName>
        <active>true</active>
        <label>Hub</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Toelichting__c</fullName>
        <label>Toelichting</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hub/Building Site</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>Locations</relationshipLabel>
        <relationshipName>Locations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Locatie</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locaties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projecten__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Projectcode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projecten</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Projectmember__c.object
<CustomObject>
    <label>Projectmember</label>
    <nameField>
        <label>Projectmember Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projectmembers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WWW__c.object
<CustomObject>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loods/HUB</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Projectmember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Aanvrager</description>
        <inlineHelpText>Dit invulveld is bedoeld om de aanvrager te benoemen.</inlineHelpText>
        <label>Aanvrager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Projectmember__c.Project__c</field>
                <operation>equals</operation>
                <valueField>$Source.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Projectmember__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WWW</label>
    <nameField>
        <displayFormat>WWW-{0}</displayFormat>
        <label>WWW Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WWW</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WWW_Detail__c.object
<CustomObject>
    <description>Who What Where
Wie Wat Waar</description>
    <fields>
        <fullName>Arrival_Truck_On_Hub__c</fullName>
        <label>Arrival Truck On Hub</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Arrival_Truck_On_Project__c</fullName>
        <label>Datum en tijd klaargezet</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Compleet_klaargezet__c</fullName>
        <label>Compleet klaargezet</label>
        <picklist>
            <picklistValues>
                <fullName>Ja</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nee</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Damage_Package__c</fullName>
        <label>Damage Package</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Einddatum_opslag__c</fullName>
        <label>Einddatum opslag</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipName>Itemlocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_Of_Items__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Aantal</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Projectmember__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Projectmember</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Project__c</field>
                <operation>equals</operation>
                <valueField>Projectmember__c.Project__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Projectmember__c</referenceTo>
        <relationshipName>Itemlocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reden_niet_compleet_uigevoerd__c</fullName>
        <label>Reden niet compleet uitgevoerd</label>
        <picklist>
            <picklistValues>
                <fullName>(deels) niet aanwezig</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stuk</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Toelichting__c</fullName>
        <label>Toelichting</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>WWW__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>WWW</label>
        <referenceTo>WWW__c</referenceTo>
        <relationshipLabel>WWW-Detail (WWW)</relationshipLabel>
        <relationshipName>WWW_Detail1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WWW-Detail</label>
    <nameField>
        <displayFormat>WWW-D-{0}</displayFormat>
        <label>WWW Details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WWW-Detail</pluralLabel>
    <recordTypes>
        <fullName>Delivered_2_Hub</fullName>
        <active>true</active>
        <label>Ontvangen</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewDeliveredExtensionTest.cls
@isTest
private class NewDeliveredExtensionTest {

	@testSetup static void setup() {
		TestDataGenerator.fillTriggerSwitcherValues();

		Account account = TestDataGenerator.createBouwticketAccount('testAccount');
        Contact contact = TestDataGenerator.createTestContact(account);

        Projecten__c project = TestDataGenerator.createTestProject(account, 'testestest');
        Projectmember__c member = TestDataGenerator.createTestProjectMember(project, contact);
        Hub_Building_Site__c buldingSite = TestDataGenerator.createTestHub('Test Hub', project);

        Item__c item = TestDataGenerator.createTestItem('TestItem', 1);
        Location__c hublocationParent = TestDataGenerator.createTestHublocationParent('20C3', buldingSite);
        List<Location__c> hublocationChilds = TestDataGenerator.createTestHublocationChildren(buldingSite, hublocationParent);

        WWW__c www = TestDataGenerator.createTestWww(project, item, buldingSite);
	}

	@isTest static void test_createOntvangen() {
		WWW__c www = [Select Id, Name from WWW__c limit 1];
        Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];

        Test.startTest();
        	WWW_Detail__c det = new WWW_Detail__c();

        	ApexPages.StandardController sc = new ApexPages.StandardController(det);
        	NewDeliveredExtension ctrl = new NewDeliveredExtension(sc);

        	PageReference tpageRef = Page.ChoseRecordType;
	        Test.setCurrentPage(tpageRef);

	        List<SelectOption> recTypes = ctrl.getrecordTypes();
	        ctrl.isChecked = recTypes.get(3).getValue();
	        System.assertNotEquals(null, ctrl.isChecked, 'Record Type for WWW Detail is not selected. Should be selected Ontvangen record type');

	        tpageRef = ctrl.goToNewView();
	        Test.setCurrentPage(tpageRef);
	        ctrl = new NewDeliveredExtension(sc);
	        System.assertNotEquals(false, ctrl.delToHub, 'Error in constructor. Not Ontvangen record type selected');

	        ctrl.detail.WWW__c = www.Id;
	        ctrl.setWWW();

	        ctrl.detail.Location__c = hublocationParent.Id;
	        ctrl.detail.Number_Of_Items__c = 10;
	        ctrl.detail.Damage_Package__c = 'No';

	        ctrl.getTimes();

	        System.currentPageReference().getParameters().put('Arrival_Truck_On_Hub__c','25.04.2017');
	        System.currentPageReference().getParameters().put('Einddatum_opslag__c','29.04.2017');

	        ctrl.getSubs();

	        System.assertNotEquals(0, ctrl.sublocations1.size(), 'No sublocations for use');

        	for(SubLocation subLoc : ctrl.sublocations1) {
        		subLoc.isChecked = true;
        	}

        	ctrl.saveDetail();
        	WWW_Detail__c toCheck = [Select Id, RecordType.Name from WWW_Detail__c where RecordType.DeveloperName = 'Delivered_2_Hub' limit 1];
        	System.assertEquals(toCheck.Id, ctrl.detail.Id, 'Detail record was not created');
        Test.stopTest();
	}

	@isTest static void test_createOntvangenNegative() {
		WWW__c www = [Select Id, Name from WWW__c limit 1];
        Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];

        Test.startTest();
        	WWW_Detail__c det = new WWW_Detail__c();

        	ApexPages.StandardController sc = new ApexPages.StandardController(det);
        	NewDeliveredExtension ctrl = new NewDeliveredExtension(sc);

        	PageReference tpageRef = Page.ChoseRecordType;
	        Test.setCurrentPage(tpageRef);

	        List<SelectOption> recTypes = ctrl.getrecordTypes();
	        ctrl.isChecked = recTypes.get(3).getValue();
	        System.assertNotEquals(null, ctrl.isChecked, 'Record Type for WWW Detail is not selected. Should be selected Ontvangen record type');

	        tpageRef = ctrl.goToNewView();
	        Test.setCurrentPage(tpageRef);
	        ctrl = new NewDeliveredExtension(sc);
	        System.assertNotEquals(false, ctrl.delToHub, 'Error in constructor. Not Ontvangen record type selected');

	        ctrl.detail.WWW__c = www.Id;
	        ctrl.setWWW();

	        ctrl.detail.Location__c = hublocationParent.Id;
	        ctrl.detail.Damage_Package__c = 'No';

	        System.currentPageReference().getParameters().put('Arrival_Truck_On_Hub__c','25.04.2017');
	        System.currentPageReference().getParameters().put('Einddatum_opslag__c','29.04.2017');

	        ctrl.getSubs();

	        System.assertNotEquals(0, ctrl.sublocations1.size(), 'No sublocations for use');

        	ctrl.saveDetail();
        Test.stopTest();
	}

	@isTest static void test_createAfleveren() {
		WWW__c www = [Select Id, Name from WWW__c limit 1];
        Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];

    	/** CREATE TEST ONTVANGEN **/
    	TestDataGenerator.createTestWwwDetailOntvangen(www, hublocationParent, 10);
    	/** END CREATE TEST ONTVANGEN **/

    	WWW_Detail__c det = new WWW_Detail__c();

    	ApexPages.StandardController sc = new ApexPages.StandardController(det);
    	NewDeliveredExtension ctrl = new NewDeliveredExtension(sc);

    	PageReference tpageRef = Page.ChoseRecordType;
        Test.setCurrentPage(tpageRef);

        List<SelectOption> recTypes = ctrl.getrecordTypes();
        ctrl.isChecked = recTypes.get(0).getValue();
        System.assertNotEquals(null, ctrl.isChecked, 'Record Type for WWW Detail is not selected. Should be selected Afleveren record type');

	    Test.startTest();
	        tpageRef = ctrl.goToNewView();
	        Test.setCurrentPage(tpageRef);
	        ctrl = new NewDeliveredExtension(sc);
	        System.assertNotEquals(false, ctrl.delToProj, 'Error in constructor. Not Afleveren record type selected');

	        ctrl.detail.WWW__c = www.Id;
	        ctrl.setWWW();

	        ctrl.detail.Number_Of_Items__c = 5;
        	ctrl.detail.Compleet_klaargezet__c = 'Ja';

        	List<SelectOption> locsForAfleveren = ctrl.getLocationsForDelToPr();

        	ctrl.detail.Location__c = locsForAfleveren.get(1).getValue();

        	ctrl.getOccupiedSubs();
        	for (AfleverenSublocs subLoc : ctrl.occupiedSublocs) {
        		subLoc.isChecked = true;
        	}

        	System.currentPageReference().getParameters().put('Arrival_Truck_On_Project__c', '27.04.2017');

        	ctrl.saveDetail();

        	/********************************************/
        	WWW_Detail__c det2 = new WWW_Detail__c();

	        ctrl.isChecked = recTypes.get(0).getValue();
        	tpageRef = ctrl.goToNewView();
	        Test.setCurrentPage(tpageRef);
	        sc = new ApexPages.StandardController(det2);
	        ctrl = new NewDeliveredExtension(sc);
	        System.assertNotEquals(false, ctrl.delToProj, 'Error in constructor. Not Afleveren record type selected second type');

	        ctrl.detail.WWW__c = www.Id;
	        ctrl.setWWW();

	        ctrl.detail.Number_Of_Items__c = 5;
        	ctrl.detail.Compleet_klaargezet__c = 'Nee';
        	ctrl.detail.Reden_niet_compleet_uigevoerd__c = 'Stuk';
        	ctrl.detail.Toelichting__c = 'Test decription';

        	locsForAfleveren = ctrl.getLocationsForDelToPr();

        	ctrl.detail.Location__c = locsForAfleveren.get(1).getValue();

        	ctrl.getOccupiedSubs();
        	for (AfleverenSublocs subLoc : ctrl.occupiedSublocs) {
        		subLoc.isChecked = true;
        	}

        	System.currentPageReference().getParameters().put('Arrival_Truck_On_Project__c', '29.04.2017');

        	ctrl.saveDetail();
        Test.stopTest();
    }

    @isTest static void test_failCreateRecvords() {
		WWW__c www = [Select Id, Name from WWW__c limit 1];
        Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];

        Test.startTest();
        	WWW_Detail__c det = new WWW_Detail__c();

        	ApexPages.StandardController sc = new ApexPages.StandardController(det);
        	NewDeliveredExtension ctrl = new NewDeliveredExtension(sc);

        	PageReference tpageRef = Page.ChoseRecordType;
	        Test.setCurrentPage(tpageRef);

	        List<SelectOption> recTypes = ctrl.getrecordTypes();
	        ctrl.isChecked = recTypes.get(3).getValue();
	        System.assertNotEquals(null, ctrl.isChecked, 'Record Type for WWW Detail is not selected. Should be selected Ontvangen record type');

	        tpageRef = ctrl.goToNewView();
	        Test.setCurrentPage(tpageRef);
	        ctrl = new NewDeliveredExtension(sc);
	        System.assertNotEquals(false, ctrl.delToHub, 'Error in constructor. Not Ontvangen record type selected');

	        ctrl.detail.WWW__c = www.Id;
	        ctrl.setWWW();

	        ctrl.detail.Location__c = hublocationParent.Id;
	        ctrl.detail.Number_Of_Items__c = 10;
	        ctrl.detail.Damage_Package__c = 'No';

	        ctrl.getTimes();

	        System.currentPageReference().getParameters().put('Arrival_Truck_On_Hub__c','25.04.2017');
	        System.currentPageReference().getParameters().put('Einddatum_opslag__c','29.04.2017');

	        ctrl.getSubs();

	        System.assertNotEquals(0, ctrl.sublocations1.size(), 'No sublocations for use');

        	for(SubLocation subLoc : ctrl.sublocations1) {
        		subLoc.isChecked = true;
        	}

        	delete www;

        	ctrl.saveDetail();
        Test.stopTest();
	}

	@isTest static void test_returnBackToSelectRecordType() {
		WWW__c www = [Select Id, Name from WWW__c limit 1];
        Location__c hublocationParent = [Select Id, Name from Location__c where Name = '20C3' limit 1];

        Test.startTest();
        	WWW_Detail__c det = new WWW_Detail__c();

        	ApexPages.StandardController sc = new ApexPages.StandardController(det);
        	NewDeliveredExtension ctrl = new NewDeliveredExtension(sc);

        	PageReference tpageRef = Page.ChoseRecordType;
	        Test.setCurrentPage(tpageRef);

	        List<SelectOption> recTypes = ctrl.getrecordTypes();
	        ctrl.isChecked = recTypes.get(3).getValue();
	        System.assertNotEquals(null, ctrl.isChecked, 'Record Type for WWW Detail is not selected. Should be selected Ontvangen record type');

	        tpageRef = ctrl.goToNewView();
	        Test.setCurrentPage(tpageRef);
	        ctrl = new NewDeliveredExtension(sc);
	        System.assertNotEquals(false, ctrl.delToHub, 'Error in constructor. Not Ontvangen record type selected');

        	ctrl.redBack();
        Test.stopTest();
	}

}