src/objects/Hub_Building_Site__c.object
<CustomObject>
    <label>Hub/Bouwplaats</label>
    <nameField>
        <label>Hub/Buildinglocation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hub/Bouwplaats</pluralLabel>
    <recordTypes>
        <fullName>Hub</fullName>
        <active>true</active>
        <label>Hub</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Diameter__c</fullName>
        <inlineHelpText>Diameter in mm</inlineHelpText>
        <label>Diameter</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Kind_Of_Packages__c</fullName>
        <inlineHelpText>Let op: de geselecteerde verpakking moet de eenheid zijn waarop het item afgeroepen gaat worden. Dus per stuk leveren is verpakking stuks of als de klant het per doos wil is de verpakking doos</inlineHelpText>
        <label>Kind Of Packages</label>
        <picklist>
            <picklistValues>
                <fullName>Balen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Big Bag</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bok</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boxen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bundels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Container</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deellading vrachtwagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dozen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flessen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasbok Hout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glasbok Staal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSA BAM Kar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Haspels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kannen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kartons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kooikar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kratten</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Los gestort</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pakken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pallets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rollen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Set</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stuks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tanks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vaten</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volledige vrachtwagen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zakken</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Kleur__c</fullName>
        <label>Kleur</label>
        <picklist>
            <picklistValues>
                <fullName>Aluminium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antraciet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beige</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beuken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bordeaux</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bruin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Donkerblauw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eiken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grijs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Groen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kersen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lichtblauw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oranje</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paars</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rood</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rose</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RVS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zwart</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Materiaal__c</fullName>
        <label>Materiaal</label>
        <picklist>
            <picklistValues>
                <fullName>Aluminium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Glas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hout</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kunststof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MDF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Metaal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Papier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plastic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plexiglas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rubber</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Steen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Stof</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trespa</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Merk__c</fullName>
        <label>Merk</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sizes__c</fullName>
        <formula>&apos;L: &apos; +TEXT(Length__c)+ &apos; x W: &apos;+ TEXT(Width__c) + &apos; x H: &apos; + TEXT(Height__c)</formula>
        <label>Sizes</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Staat__c</fullName>
        <label>Staat</label>
        <picklist>
            <picklistValues>
                <fullName>Beschadigd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gebruikt &gt; Inzetbaar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gebruikt &gt; Inzetbaar &gt; Gedemonteerd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gebruikt &gt; Niet inzetbaar &gt; Repareren</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gebruikt &gt; Niet inzetbaar &gt; Schoonmaken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gereviseerd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nader te bepalen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nieuw</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Onbekend</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WWW__c.object
<CustomObject>
    <fields>
        <fullName>Curr_Items_To_Invoke__c</fullName>
        <formula>Total_Items_Delivered_Hub__c - Total_Items_Invoked__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Huidige items die we kunnen oproepen (items geleverd op Hub - opgeroepen items)</inlineHelpText>
        <label>Curr Items To Invoke</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hub_Building_Site__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loods/HUB</label>
        <referenceTo>Hub_Building_Site__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Item</label>
        <referenceTo>Item__c</referenceTo>
        <relationshipLabel>WWW</relationshipLabel>
        <relationshipName>WWW</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>WWW</label>
    <nameField>
        <displayFormat>WWW-{0}</displayFormat>
        <label>WWW Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WWW</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ItemsList.cls
/**
 * Wrapper class for Items to Afroepen with comperable methods
 *
 * @version     1.01 11 June 2017
 * @author      Oleg Bogdanovych
 */

global with sharing class ItemsList implements Comparable {
	public Boolean isSelected {get; set;}
	public WWW__c wwwRecord {get; set;}
	public Decimal itemsToInvoke {get; set;}
	public Boolean show {get; set;}

	public ItemsList(WWW__c www, Boolean show) {
		this.wwwRecord = www;
		this.isSelected = false;
		this.show = show;
	}

	public static final String ASCENDING = 'ASCENDING';
    public static String SortDirection;
    public static String SortField;

	global Integer compareTo(Object compareTo) {
		ItemsList compateToItem = (ItemsList) compareTo;

		if (SortField == 'Name') {
            return compareToName(compareTo);
        }

        if (SortField == 'Staat') {
            return compareToStaat(compareTo);
        }

        if (SortField == 'Maten') {
            return compareToMaten(compareTo);
        }

        if (SortField == 'Diameter') {
            return compareToDiameter(compareTo);
        }

        if (SortField == 'Merk') {
            return compareToMerk(compareTo);
        }

        if (SortField == 'Material') {
            return compareToMaterial(compareTo);
        }

        if (SortField == 'Kleur') {
            return compareToKleur(compareTo);
        }

        if (SortField == 'Type_verpakking') {
            return compareToTypeVerpakking(compareTo);
        }

        if (SortField == 'wat_nog_op_te_roepen_is') {
            return compareToItemsLeft(compareTo);
        }

        if (SortField == 'Loods/HUB') {
            return compareToHub(compareTo);
        }

        return 0;
    }

    public Integer compareToName(Object obj) {
    	ItemsList item = (ItemsList)(obj);

        if (this.wwwRecord.Item__r.Name > item.wwwRecord.Item__r.Name) {
            if (SortDirection == ASCENDING) {
            	return 1;
            } else {
                return -1;
            }
        }

        if (this.wwwRecord.Item__r.Name == item.wwwRecord.Item__r.Name) {
            return 0;
        }

        if (SortDirection == ASCENDING) {
            return -1;
        } else {
            return 1;
        }
    }

    public Integer compareToStaat(Object obj) {
    	ItemsList item = (ItemsList)(obj);

        if (this.wwwRecord.Item__r.Staat__c > item.wwwRecord.Item__r.Staat__c) {
            if (SortDirection == ASCENDING) {
            	return 1;
            } else {
                return -1;
            }
        }

        if (this.wwwRecord.Item__r.Staat__c == item.wwwRecord.Item__r.Staat__c) {
            return 0;
        }

        if (SortDirection == ASCENDING) {
            return -1;
        } else {
            return 1;
        }
    }

    public Integer compareToMaten(Object obj) {
    	ItemsList item = (ItemsList)(obj);

        if (this.wwwRecord.Item__r.Sizes__c > item.wwwRecord.Item__r.Sizes__c) {
            if (SortDirection == ASCENDING) {
            	return 1;
            } else {
                return -1;
            }
        }

        if (this.wwwRecord.Item__r.Sizes__c == item.wwwRecord.Item__r.Sizes__c) {
            return 0;
        }

        if (SortDirection == ASCENDING) {
            return -1;
        } else {
            return 1;
        }
    }

    public Integer compareToDiameter(Object obj) {
    	ItemsList item = (ItemsList)(obj);

        if (this.wwwRecord.Item__r.Diameter__c > item.wwwRecord.Item__r.Diameter__c) {
            if (SortDirection == ASCENDING) {
            	return 1;
            } else {
                return -1;
            }
        }

        if (this.wwwRecord.Item__r.Diameter__c == item.wwwRecord.Item__r.Diameter__c) {
            return 0;
        }

        if (SortDirection == ASCENDING) {
            return -1;
        } else {
            return 1;
        }
    }

    public Integer compareToMerk(Object obj) {
    	ItemsList item = (ItemsList)(obj);

        if (this.wwwRecord.Item__r.Merk__c > item.wwwRecord.Item__r.Merk__c) {
            if (SortDirection == ASCENDING) {
            	return 1;
            } else {
                return -1;
            }
        }

        if (this.wwwRecord.Item__r.Merk__c == item.wwwRecord.Item__r.Merk__c) {
            return 0;
        }

        if (SortDirection == ASCENDING) {
            return -1;
        } else {
            return 1;
        }
    }

    public Integer compareToMaterial(Object obj) {
    	ItemsList item = (ItemsList)(obj);

        if (this.wwwRecord.Item__r.Materiaal__c > item.wwwRecord.Item__r.Materiaal__c) {
            if (SortDirection == ASCENDING) {
            	return 1;
            } else {
                return -1;
            }
        }

        if (this.wwwRecord.Item__r.Materiaal__c == item.wwwRecord.Item__r.Materiaal__c) {
            return 0;
        }

        if (SortDirection == ASCENDING) {
            return -1;
        } else {
            return 1;
        }
    }

    public Integer compareToKleur(Object obj) {
    	ItemsList item = (ItemsList)(obj);

        if (this.wwwRecord.Item__r.Kleur__c > item.wwwRecord.Item__r.Kleur__c) {
            if (SortDirection == ASCENDING) {
            	return 1;
            } else {
                return -1;
            }
        }

        if (this.wwwRecord.Item__r.Kleur__c == item.wwwRecord.Item__r.Kleur__c) {
            return 0;
        }

        if (SortDirection == ASCENDING) {
            return -1;
        } else {
            return 1;
        }
    }

    public Integer compareToTypeVerpakking(Object obj) {
    	ItemsList item = (ItemsList)(obj);

        if (this.wwwRecord.Item__r.Kind_Of_Packages__c > item.wwwRecord.Item__r.Kind_Of_Packages__c) {
            if (SortDirection == ASCENDING) {
            	return 1;
            } else {
                return -1;
            }
        }

        if (this.wwwRecord.Item__r.Kind_Of_Packages__c == item.wwwRecord.Item__r.Kind_Of_Packages__c) {
            return 0;
        }

        if (SortDirection == ASCENDING) {
            return -1;
        } else {
            return 1;
        }
    }

    public Integer compareToItemsLeft(Object obj) {
    	ItemsList item = (ItemsList)(obj);

        if (this.wwwRecord.Curr_Items_To_Invoke__c > item.wwwRecord.Curr_Items_To_Invoke__c) {
            if (SortDirection == ASCENDING) {
            	return 1;
            } else {
                return -1;
            }
        }

        if (this.wwwRecord.Curr_Items_To_Invoke__c == item.wwwRecord.Curr_Items_To_Invoke__c) {
            return 0;
        }

        if (SortDirection == ASCENDING) {
            return -1;
        } else {
            return 1;
        }
    }

    public Integer compareToHub(Object obj) {
    	ItemsList item = (ItemsList)(obj);

        if (this.wwwRecord.Hub_Building_Site__r.Name > item.wwwRecord.Hub_Building_Site__r.Name) {
            if (SortDirection == ASCENDING) {
            	return 1;
            } else {
                return -1;
            }
        }

        if (this.wwwRecord.Hub_Building_Site__r.Name == item.wwwRecord.Hub_Building_Site__r.Name) {
            return 0;
        }

        if (SortDirection == ASCENDING) {
            return -1;
        } else {
            return 1;
        }
    }
}